Add user without opss_user role to seed file
UKGovernmentBEIS/beis-opss-psd pull request #1029
Opened 2020-11-13 17:07 UTC by KyleMacPherson

This PR adds a user to our seed file that does not have `opss_user` role. We currently do not have a this kind of user and this will be useful to test the different flow available to trading standards users.

## Checklist:
- [x] Have you documented your changes in the pull request description?
- [ ] Does the change present any security considerations?
- [ ] Is any gem functionality overloaded? Eg: Devise controller methods being overloaded.
- [ ] Has acceptance criteria been tested by a peer?
- [ ] Has the CHANGELOG been updated? (If change is worth telling users about.)

### General testing (author)
- [ ] Test without JavaScript
- [ ] Test on small screen

### Accessibility testing (author)
- [ ] Works keyboard only
- [ ] Tested with one screen reader
- [ ] Zoom page to 400% - content still visible
- [ ] Disable CSS - does content make sense and appear in a logical order?

2020-11-13 17:26 UTC, slorek requested changes

2020-11-13 17:26 UTC, slorek commented on db/seeds.rb
> +      team: enforcement,
Please change: `organisation` and `team` should be different as otherwise they will be on the same OPSS team as the OPSS users.

2020-11-16 12:41 UTC, KyleMacPherson commented on db/seeds.rb
> +      team: enforcement,
@slorek This looking better now?

2020-11-17 10:31 UTC, slorek approved these changes

2020-11-17 10:40 UTC, merged