Add fields to csv export
UKGovernmentBEIS/beis-opss-psd pull request #1042
Opened 2020-11-23 14:52 UTC by KyleMacPherson

https://trello.com/c/bKJRQ5WW/817-add-date-related-fields-to-export

## Description
Add date created, date updated and date closed to the exported csv file.
- Date created and date updated based upon the investigation's created_at/updated_at fields.
- Date closed based upon the created_at field of an UpdateStatus activity which recorded the investigation being closed

[cases (14).xlsx](https://github.com/UKGovernmentBEIS/beis-opss-psd/files/5583781/cases.14.xlsx)

## Checklist:
- [x] Have you documented your changes in the pull request description?
- [ ] Does the change present any security considerations?
- [ ] Is any gem functionality overloaded? Eg: Devise controller methods being overloaded.
- [ ] Has acceptance criteria been tested by a peer?
- [ ] Has the CHANGELOG been updated? (If change is worth telling users about.)

### General testing (author)
- [ ] Test without JavaScript
- [ ] Test on small screen

### Accessibility testing (author)
- [ ] Works keyboard only
- [ ] Tested with one screen reader
- [ ] Zoom page to 400% - content still visible
- [ ] Disable CSS - does content make sense and appear in a logical order?

2020-11-23 16:16 UTC, slorek requested changes
We'll also need to check how this affects performance as this endpoint is quite slow already.

I would suggest it might be useful to add a `date_closed` attribute to `Investigation` as part of this change to avoid this roundabout way of finding the date which will be quite slow and not 100% reliable. We just need to remember to blank it again when a case is reopened.

2020-11-23 16:16 UTC, slorek commented on app/models/investigation/allegation.rb
> +      activities.where(title: "Allegation closed").last
Please change: Use `type: "AuditActivity::Investigation::UpdateStatus"` (as well as being less brittle, you can do this on the parent class and avoid the need to define the method differently on all the subclasses. It will also simplify the tests).

I'd also suggest returning `nil` if the case is not closed (`is_closed?`). This would avoid taking a 'reopened' activity as closed.

2020-11-23 16:27 UTC, KyleMacPherson commented on app/models/investigation/allegation.rb
> +      activities.where(title: "Allegation closed").last
@slorek does `"AuditActivity::Investigation::UpdateStatus"` always relate to an activity that closes an investigation. I imagined that the status could be updated in a different way (perhaps opened again as you mention).

Good idea with regard to returning nil if closed is not closed, will do 👍

2020-11-24 10:43 UTC, StupidCodeFactory approved these changes

2020-11-24 10:43 UTC, StupidCodeFactory commented on spec/requests/export_investigations_spec.rb
> +            aggregate_failures do
Suggestion: we usually add the `:aggregate_failures` as metadata of the `it` block 
```ruby
it "exports closing date in date_closed column", :aggregate_failures do
  # ...
end
```

reduces the number of lines in the test

2020-11-24 10:43 UTC, StupidCodeFactory commented on app/controllers/investigations_controller.rb
> +        @investigations = @answer.records(includes: %i[complainant creator_user products owner_team owner_user activities])
Suggestion: good spot that you've thought about the n+1 queries! 👏 
This will however loads a tone of activities. I wonder if by just adding 
```ruby
class Investigation < ApplicationRecord
  has_many :updated_status_activities`, -> { where(type: "AuditActivity::Investigation::UpdateStatus").order(created_at: :desc) }
end

# in the controller 
@answer.records(includes: %i[complainant creator_user products owner_team owner_user updated_status_activities])

```
This would generate a little more optimised query and only loads those audit records.
This export is already a bit slow and we need  to be careful that report can still be genrated within the web request's timeout.

2020-11-25 14:13 UTC, closed without merging