Add which standard was the product tested against
UKGovernmentBEIS/beis-opss-psd pull request #1046
Opened 2020-11-24 16:58 UTC by StupidCodeFactory

## Description

## Checklist:
- [ ] Have you documented your changes in the pull request description?
- [ ] Does the change present any security considerations?
- [ ] Is any gem functionality overloaded? Eg: Devise controller methods being overloaded.
- [ ] Has acceptance criteria been tested by a peer?
- [ ] Has the CHANGELOG been updated? (If change is worth telling users about.)

### General testing (author)
- [ ] Test without JavaScript
- [ ] Test on small screen

### Accessibility testing (author)
- [ ] Works keyboard only
- [ ] Tested with one screen reader
- [ ] Zoom page to 400% - content still visible
- [ ] Disable CSS - does content make sense and appear in a logical order?

2020-12-10 10:41 UTC, KyleMacPherson requested changes
Nice work Yann, looks like it brings the test results stuff in line with the pattern we use elsewhere which seems like a good idea! Just had a couple of comments/questions

2020-12-10 10:41 UTC, KyleMacPherson commented on app/helpers/tests_helper.rb
> +        key: { text: "Standards" },
Should the strings here be in the en.yml file?

2020-12-10 10:41 UTC, KyleMacPherson commented on app/views/investigations/test_results/_form.html.erb
> +<%= form.govuk_input :standards_product_was_tested_against, hint: "For example, EN71. Use comma to separate multiple standards.", label: "Which standard was the product tested against?", value: form.
Think the strings here should be in en.yml too

2020-12-10 10:41 UTC, KyleMacPherson commented on db/migrate/20201125105949_add_standars_product_was_testing_against_to_tests.rb
> +      # TODO: add default to empty array in later migration
Any reason not to do this in this PR?

2020-12-10 10:41 UTC, KyleMacPherson commented on lib/active_model/types/comma_separated_list.rb
> +    class CommaSeparatedList < ActiveRecord::Type::Value
Is this related to this change?

2020-12-10 10:41 UTC, KyleMacPherson commented on app/controllers/investigations/test_results_controller.rb
> +    render "edit"
Seems like a bit of a smell to have 2 renders of the same view in the same controller. Can`UpdateTestResult` fail if the `test_result_form` is valid? If it does fail will errors be shown on the page render?

2020-12-10 12:06 UTC, nasirkhanbeis commented
spotted few issues 
1. regression issue - cannot create allegation/enquiry as opss user - returns service error after I submit the contact details page
2. TS flow - add test result - standard field is not mandatory- when I submit with empty field then it should throw error
3. Edit test result - edit standard field doesn't record in activity log

2020-12-10 14:46 UTC, StupidCodeFactory commented on db/migrate/20201125105949_add_standars_product_was_testing_against_to_tests.rb
> +      # TODO: add default to empty array in later migration
Yeah I want to do this in a seperate PR.

2020-12-10 14:47 UTC, StupidCodeFactory commented on app/views/investigations/test_results/_form.html.erb
> +<%= form.govuk_input :standards_product_was_tested_against, hint: "For example, EN71. Use comma to separate multiple standards.", label: "Which standard was the product tested against?", value: form.
No we only use `I18n` for error message and string inside models. I would have been happy to have everything in `I18n` but this is not what we've been doing so far.

2020-12-10 14:51 UTC, StupidCodeFactory commented on app/helpers/tests_helper.rb
> +        key: { text: "Standards" },
no we don't really use I18n in views. It is mostly error model's messages.

2020-12-10 14:53 UTC, StupidCodeFactory commented on lib/active_model/types/comma_separated_list.rb
> +    class CommaSeparatedList < ActiveRecord::Type::Value
yes required here https://github.com/UKGovernmentBEIS/beis-opss-psd/pull/1046/files#diff-6e6c15bed988a566b6e12a23f5dd5794c5da1a06ea8e4a491149b1b74fad6602R3 

and used here :

https://github.com/UKGovernmentBEIS/beis-opss-psd/pull/1046/files#diff-47435d37d60442ab18b9dc65f83c618abeb5c69aa5d48b80925dea2a6f508feeR14

2020-12-10 15:19 UTC, StupidCodeFactory commented on app/controllers/investigations/test_results_controller.rb
> +    render "edit"
This is the pattern we've been using throughout the code base. I'm not particularly keen on it, particularly that we don't pass the form to service object but a bunch of random key value pairs, making the interface of service object totally unpredictable. 
It then necessary for controller to 1) validate the form, 2) know what and how to pass to the service object, 3) run the service object 4) hand the result

In my opinion the controller is doing far too much but that's the abstraction we all agreed on and the we have been following in most places.

2020-12-10 15:30 UTC, slorek commented on app/controllers/investigations/test_results_controller.rb
> +    render "edit"
I think this is a relatively complex method, but overall is consistent with others as Yann says.

2020-12-10 15:38 UTC, slorek commented on app/models/audit_activity/risk_assessment/risk_assessment_added.rb
> +  def title(_ = nil)
```suggestion
  def title(*)
```

2020-12-10 15:53 UTC, slorek requested changes
Some minor changes needed from my first scan of the code. I'll test the review app next.

2020-12-10 15:53 UTC, slorek commented on app/models/audit_activity/test/result.rb
>  class AuditActivity::Test::Result < AuditActivity::Test::Base
Please change: When overriding `from` you also need to override the `notify_relevant_users` callback method inherited from `Activity` to prevent a second duplicate e-mail being sent, which can also cause unexpected behaviour in tests. See `AuditActivity::Test::TestResultUpdated` for an example of this.

2020-12-10 15:53 UTC, slorek commented on app/models/test.rb
> +  belongs_to :product, optional: false
Please check on production whether there is any data which might cause a break with this change.

2020-12-10 15:53 UTC, slorek commented on app/views/investigations/test_results/_form.html.erb
> +<%= form.govuk_input :standards_product_was_tested_against, hint: "For example, EN71. Use comma to separate multiple standards.", label: "Which standard was the product tested against?", value: form.
I think we agreed to move most strings to I18n over time, not just models. This would be ideal, but not a big deal.

2020-12-10 15:53 UTC, slorek commented on db/migrate/20201125105949_add_standars_product_was_testing_against_to_tests.rb
> +class AddStandarsProductWasTestingAgainstToTests < ActiveRecord::Migration[6.0]
Please change: typos:
```suggestion
class AddStandardsProductWasTestedAgainstToTests < ActiveRecord::Migration[6.0]
```

2020-12-10 15:53 UTC, slorek commented on spec/fixtures/files/new_test_result.txt
> +new test ressult
```suggestion
new test result
```

2020-12-11 11:49 UTC, StupidCodeFactory commented on app/models/test.rb
> +  belongs_to :product, optional: false
I've checked with:
```ruby
 Test::Result.left_joins(:product).where(products: {id: nil}).count # => 0
```

so it should be fine

2020-12-11 11:50 UTC, StupidCodeFactory commented on app/views/investigations/test_results/_form.html.erb
> +<%= form.govuk_input :standards_product_was_tested_against, hint: "For example, EN71. Use comma to separate multiple standards.", label: "Which standard was the product tested against?", value: form.
ok I wasn't aware of this! This Pr is already quite big, I'd like to avoid adding more moving part to this PR

2020-12-11 12:42 UTC, StupidCodeFactory commented on .slim-lint.yml
> +      - 'app/views/investigations/creation_flow/enquiry_details.html.slim'
Did not want to add noise to this big Pr. will do a follow up Pr to convert this templates and remove this from the slim linter

2020-12-11 15:52 UTC, KyleMacPherson approved these changes

2020-12-14 15:01 UTC, slorek requested changes
Please change: looks like the wrong class was used for the field label compared to the others.

<img width="934" alt="Screenshot 2020-12-14 at 14 58 21" src="https://user-images.githubusercontent.com/408371/102096729-f0822700-3e1c-11eb-8238-4861a33d2e2e.png">

On edit (but not add), I can add multiple "blank" test standards, e.g: 

<img width="838" alt="Screenshot 2020-12-14 at 15 00 56" src="https://user-images.githubusercontent.com/408371/102096952-30490e80-3e1d-11eb-860a-ddb683e6c155.png">

2020-12-14 15:49 UTC, slorek approved these changes

2020-12-14 16:31 UTC, tobyhughes commented
Very minor change, need to update hint text: 


![image](https://user-images.githubusercontent.com/56029300/102107323-89b73a80-3e29-11eb-9534-d582bc6a3063.png)

Should be: `For example, EN71. Use a comma to separate multiple standards.`
 (it's just missing the 'a')

2020-12-14 16:42 UTC, tobyhughes commented
Activity record is looking a little strange 

![image](https://user-images.githubusercontent.com/56029300/102108213-8c665f80-3e2a-11eb-8b20-8c6eed2d3e44.png)

Should reflect list of fields on form:

`Product:`
`Legislation:`
`Standards:`
`Test date:`
`Test result:`
`Further details:`
`Attached:` 

Then links to view the product and the test result (see corrective action activity log)

2020-12-16 14:07 UTC, StupidCodeFactory commented
@tobyhughes could you have another look I've fixed the audit.
<img width="1093" alt="Screenshot 2020-12-16 at 14 40 08" src="https://user-images.githubusercontent.com/100796/102358918-040dc900-3fa8-11eb-8645-50c82c13dbe4.png">

2020-12-17 08:50 UTC, nasirkhanbeis commented
Hi @StupidCodeFactory  hint text is slightly wrong,'a' in wrong place. :) 
It should read as "Use a comma to separate multiple standards " but not Use comma a to separate multiple standards

2020-12-17 08:52 UTC, nasirkhanbeis commented
Audit log looks good 
![image](https://user-images.githubusercontent.com/47983567/102465093-23a6ff00-4045-11eb-90fb-a5ee21a2f7c7.png)

2020-12-17 10:09 UTC, tobyhughes approved these changes
Looks good to me!

2020-12-17 10:10 UTC, merged