Question to determine if the product has a UKCA mark, a UKNI mark, or a CE mark
UKGovernmentBEIS/beis-opss-psd pull request #1081
Opened 2020-12-16 18:08 UTC by slorek

https://trello.com/c/AUGFmp9W/852-question-to-determine-if-the-product-has-a-ukca-mark-a-ukni-mark-or-a-ce-mark

## Description
I've gone with an Array column type which is proprietary to PostgreSQL. If this app was ever to be ported to another RDMS we would need to implement Rails' serialization.

I had to change the design slightly to use a `legend` tag instead of hint text, for accessibility.

## Checklist:
- [ ] Have you documented your changes in the pull request description?
- [ ] Does the change present any security considerations?
- [ ] Is any gem functionality overloaded? Eg: Devise controller methods being overloaded.
- [ ] Has acceptance criteria been tested by a peer?
- [ ] Has the CHANGELOG been updated? (If change is worth telling users about.)

### General testing (author)
- [ ] Test without JavaScript
- [ ] Test on small screen

### Accessibility testing (author)
- [ ] Works keyboard only
- [ ] Tested with one screen reader
- [ ] Zoom page to 400% - content still visible
- [ ] Disable CSS - does content make sense and appear in a logical order?

2020-12-16 18:35 UTC, StupidCodeFactory approved these changes
Looks good!

2020-12-16 18:35 UTC, StupidCodeFactory commented on app/helpers/products_helper.rb
> +    ).with_defaults(markings: [])
Nice! Didn't know about this nifty trick!

2020-12-17 16:32 UTC, slorek commented
Changes to the design required prior to merging.

2020-12-22 09:37 UTC, KyleMacPherson approved these changes

2020-12-22 13:38 UTC, nasirkhanbeis commented
Outstanding issues to resolve 1. regression bug around unit counts value not shown- https://trello.com/c/XrIJAjtm/863-regression-issue-in-pr-1081-units-count-is-not-saved

2020-12-22 16:56 UTC, nasirkhanbeis commented
re-tested regression issue, looking good!
Unknown is still showing as "Not provided" either we need to show Unknown or blank

2020-12-23 15:46 UTC, StupidCodeFactory requested changes
Looks good I've suggested a few improvements but I think you are missing the timestamps of the migration at the top of the `schema.rb` file

2020-12-23 15:46 UTC, StupidCodeFactory commented on app/decorators/product_decorator.rb
> +    return I18n.t(".product.unknown") if object.has_markings == "markings_unknown"
```suggestion
    return I18n.t(".product.unknown") if object.markings_unknown?
```

2020-12-23 15:46 UTC, StupidCodeFactory commented on app/decorators/product_decorator.rb
> +    return I18n.t(".product.none") if object.has_markings == "markings_no"
```suggestion
    return I18n.t(".product.none") if object.markings_no?
```

2020-12-23 15:46 UTC, StupidCodeFactory commented on app/helpers/products_helper.rb
> +    ).with_defaults(markings: [])
maybe make this a `Set.new` ?

2020-12-23 15:46 UTC, StupidCodeFactory commented on app/models/product.rb
> +  def has_markings?
I can not see where this is used? Is it redundant?

2020-12-23 15:46 UTC, StupidCodeFactory commented on db/schema.rb
> +  create_enum "has_markings_values", ["markings_yes", "markings_no", "markings_unknown"]
I think you forgot to commit migration timespamp

2020-12-23 15:46 UTC, StupidCodeFactory commented on spec/forms/product_form_spec.rb
> +        expect(form.attributes["markings"]).to eq([])
```suggestion
        expect(form).to have_attributes(markings: [])
```

2020-12-23 15:46 UTC, StupidCodeFactory commented on spec/models/product_spec.rb
> +        expect(product.has_markings?).to be true
```suggestion
        expect(product).to have_markings
```

2020-12-23 15:49 UTC, nasirkhanbeis approved these changes
looks good as expected!

2020-12-24 10:03 UTC, slorek commented
> Looks good I've suggested a few improvements but I think you are missing the timestamps of the migration at the top of the `schema.rb` file

@StupidCodeFactory there was a newer hotfix migration added and merged to master by you so the schema version is correct. The migration will still run.

2020-12-24 10:08 UTC, slorek commented on app/models/product.rb
> +  def has_markings?
Yes looks like it is now redundant.

2020-12-24 10:11 UTC, slorek commented on app/helpers/products_helper.rb
> +    ).with_defaults(markings: [])
I considered using a `Set` to avoid the de-duplication code, but the database data type is `Array` and that would be the type returned by ActiveRecord. We would depend on the casting when creating a new record. This could be confusing and have unexpected consequences.

2020-12-24 10:13 UTC, slorek commented on db/schema.rb
> +  create_enum "has_markings_values", ["markings_yes", "markings_no", "markings_unknown"]
There was a newer hotfix migration added and merged to master by you so the schema version is correct. The migration will still run.

2020-12-24 10:36 UTC, StupidCodeFactory approved these changes

2020-12-24 11:38 UTC, slorek commented on spec/forms/product_form_spec.rb
> +        expect(form.attributes["markings"]).to eq([])
`have_attributes` uses the getter method `markings` which has different behaviour we do not want to test in this instance.

2020-12-24 14:28 UTC, merged