add online recall information
UKGovernmentBEIS/beis-opss-psd pull request #1090
Opened 2020-12-21 17:40 UTC by StupidCodeFactory

Merge both Corrrective action controller and create a form to harmonise the
application code

## Description

## Checklist:
- [ ] Have you documented your changes in the pull request description?
- [ ] Does the change present any security considerations?
- [ ] Is any gem functionality overloaded? Eg: Devise controller methods being overloaded.
- [ ] Has acceptance criteria been tested by a peer?
- [ ] Has the CHANGELOG been updated? (If change is worth telling users about.)

### General testing (author)
- [ ] Test without JavaScript
- [ ] Test on small screen

### Accessibility testing (author)
- [ ] Works keyboard only
- [ ] Tested with one screen reader
- [ ] Zoom page to 400% - content still visible
- [ ] Disable CSS - does content make sense and appear in a logical order?

2021-01-11 16:02 UTC, nasirkhanbeis commented
spotted few minor issues
1. for existing  corrective actions, we should show new field with value "Not provided"
2. when I just update recall information only, activity log doesn't seem to record new changes.
![Uploading image.png…]()

2021-01-11 16:25 UTC, nasirkhanbeis commented
One more issue, corrective action in TS flow is not recored. steps to replicate
1. As TS user, open a new case, fill in all the details, follow the journey.
2. When prompted for corrective action, select yes and fill-in corrective action form, are there other actions to report? don't select any option, submit the form. Expected to throw validation error however 
  it creates case successfully with no corrective action 
![image](https://user-images.githubusercontent.com/47983567/104209407-92e7f700-5429-11eb-81bf-c568fe465201.png)

2021-01-11 17:03 UTC, nasirkhanbeis commented
re-call information field in view page to be placed after business as given in the miro board
![image](https://user-images.githubusercontent.com/47983567/104214006-db55e380-542e-11eb-845b-edf16ed8ca08.png)

2021-01-13 15:53 UTC, StupidCodeFactory commented on app/controllers/investigations/corrective_actions_controller.rb
> +          .serializable_hash(except: :further_corrctive_action)
```suggestion
          .serializable_hash
```

2021-01-13 16:00 UTC, StupidCodeFactory commented on app/models/audit_activity/corrective_action/base.rb
> -  private_class_method def self.from(corrective_action)
through exception

2021-01-13 16:02 UTC, StupidCodeFactory commented on app/models/audit_activity/corrective_action/base.rb
> +                             elsif attachment.attached?
wrap this in a method `load_legacy_audit_corrective_record`

2021-01-13 16:15 UTC, nasirkhanbeis commented
Hi @StupidCodeFactory , there's a bug in activity log, view product and view corrective action links are missing 
Add new corrective action and go to activity log 
![image](https://user-images.githubusercontent.com/47983567/104478619-6f07eb00-55ba-11eb-967c-2d7f2555c2b7.png)

2021-01-13 16:44 UTC, nasirkhanbeis commented
Another issue - Edit existing corrective action, returns error as below when I try save with recall information (any option yes, no or Not relevant returns error). Expected to save with recall information
![image](https://user-images.githubusercontent.com/47983567/104481733-091d6280-55be-11eb-912c-31fc82ffdb3f.png)

2021-01-14 11:46 UTC, tobyhughes commented
No capitalisation required on 'relevant' :

![image](https://user-images.githubusercontent.com/56029300/104587004-2efa4400-565e-11eb-85f0-e7ceacfa6565.png)

2021-01-14 12:24 UTC, nasirkhanbeis commented
Few more issues to sort on latest build 
1. recall information is missing  in activity log when new corrective action is added
2. View product details link shows with leading character '4' in activity log
3. when recall information is chosen 'No' then show value "Not published" in view page and activity log.

2021-01-15 10:00 UTC, nasirkhanbeis commented
hey @StupidCodeFactory 
Found a potential issue around activity log, when corrective action is updated, along with changes log, it updates original activity log too.

2021-01-20 10:13 UTC, slorek commented on app/models/audit_activity/corrective_action/add.rb
> +    { corrective_action_id: corrective_action.id, updates: changes }
Suggestion: I'm also looking at a pattern for achieving this separately. It seems a bit strange to pass all the new attributes from the controller to the service alongside a `changes` object which is relayed to the audit activity. Especially as it is a new object so there can be no updates. Since we receive the `corrective_action` we could just serialize the attributes here and remove all the `changes`.

2021-01-25 12:42 UTC, nasirkhanbeis commented
Re-tested latest changes on review app 1090 and spotted couple issues
1. Attachment file when replaced with new file, it replaces in original add corrective action log too.
2. When attachment description is removed, it doesn't records in activity log but shows empty log 
![image](https://user-images.githubusercontent.com/47983567/105707384-c1c29a80-5f0a-11eb-8aa2-a7603d67ab08.png)

2021-01-25 13:08 UTC, nasirkhanbeis commented
Another issue, when corrective action added in TS flow, view business link in activity log is missing(when business was added in the TS flow)

2021-01-26 10:35 UTC, nasirkhanbeis approved these changes
looking good as expected!

2021-01-27 11:15 UTC, slorek commented on app/controllers/investigations/corrective_actions_controller.rb
> +          .merge(user: current_user, investigation: investigation, changes: @corrective_action_form.changes)
We've discussed this passing of the `changes` hash through the service to the audit activity as something we want to avoid. We have a proposal for an alternative pattern in a separate PR (https://github.com/UKGovernmentBEIS/beis-opss-psd/pull/1144). It is not necessary to change this now, but it will be a little more difficult to do so afterwards if the feature is used in production, as we'll have to write a data migration. I'll leave it to you to decide whether to refactor this now or afterwards.

2021-01-27 13:12 UTC, slorek commented on app/helpers/investigations/corrective_actions_helper.rb
> +    TRUNCATED_ACTION_MAP = {
Please change: This appears to be a duplicate of `CorrectiveAction::TRUNCATED_ACTION_MAP`. Also I think it would ideally be achieved with I18n.

2021-01-27 13:37 UTC, slorek requested changes
Minor changes requested in comments.

2021-01-29 13:19 UTC, KyleMacPherson approved these changes

2021-02-01 10:58 UTC, slorek approved these changes

2021-02-01 11:21 UTC, nasirkhanbeis commented
Re-tested latest fix, looking good as expected.

2021-02-01 11:28 UTC, merged