Accident and incident
UKGovernmentBEIS/beis-opss-psd pull request #1174
Opened 2021-02-08 17:50 UTC by KyleMacPherson

## Description

## Checklist:
- [ ] Have you documented your changes in the pull request description?
- [ ] Does the change present any security considerations?
- [ ] Is any gem functionality overloaded? Eg: Devise controller methods being overloaded.
- [ ] Has acceptance criteria been tested by a peer?
- [ ] Has the CHANGELOG been updated? (If change is worth telling users about.)

### General testing (author)
- [ ] Test without JavaScript
- [ ] Test on small screen

### Accessibility testing (author)
- [ ] Works keyboard only
- [ ] Tested with one screen reader
- [ ] Zoom page to 400% - content still visible
- [ ] Disable CSS - does content make sense and appear in a logical order?

2021-02-09 10:42 UTC, nasirkhanbeis commented
Hey @KyleMacPherson  can we show audit log title more specific one? such as type added? In below case we want to show tittle Incident added instead incident or accident
![image](https://user-images.githubusercontent.com/47983567/107352203-7a6c0a80-6ac3-11eb-8af6-60be63ef9e89.png)

2021-02-09 10:51 UTC, nasirkhanbeis commented
date displayed in audit log should be in dd-mm-yyyy format but not in American format I think
![image](https://user-images.githubusercontent.com/47983567/107353229-b5bb0900-6ac4-11eb-816e-893a1204c47e.png)

2021-02-09 12:07 UTC, nasirkhanbeis commented
found couple more issues
1. cancel link on type of incident/accident page should return to supporting information tab but not to over view page
2. Additional information in accident/incident form is not being recorded in audit log 
![image](https://user-images.githubusercontent.com/47983567/107361511-662e0a80-6acf-11eb-9059-75d3f9cf7f95.png)

2021-02-09 18:57 UTC, nasirkhanbeis commented
hey @KyleMacPherson  can you also change title to specific type one either Accident or Incident depending on which one is edited . see below. title for below should read only as Accident 
![image](https://user-images.githubusercontent.com/47983567/107413368-98a82980-6b08-11eb-8411-7dd00ebc28a7.png)

2021-02-10 17:26 UTC, StupidCodeFactory requested changes

2021-02-10 17:26 UTC, StupidCodeFactory commented on app/services/add_accident_or_incident_to_case.rb
> +      metadata: audit_activity_metadata,
Please change: attach product to the activity record and remove `#product_assesed` method in the audit record

2021-02-10 17:26 UTC, StupidCodeFactory commented on app/models/investigation.rb
> +  has_many :incidents
```suggestion
  has_many :incidents, -> where(type: "Incident")
```

2021-02-10 17:26 UTC, StupidCodeFactory commented on app/models/investigation.rb
> +  has_many :accidents
```suggestion
  has_many :accidents, -> where(type: "Accident")
```

2021-02-10 17:26 UTC, StupidCodeFactory commented on app/views/investigations/accident_or_incidents/_form.html.erb
> +<%= form.hidden_field :event_type, value: @event_type %>
Please change, use active record polymorphism support by providing the type reflecting the correct `#type` to be passed to the `UnexpectedEvent` subclass which also means you can remove the "if" condition it the service class: 
```suggestion
<%= form.hidden_field :type, value: @event_type %>
```

2021-02-10 17:26 UTC, StupidCodeFactory commented on app/views/investigations/activities/accident_or_incident/_accident_or_incident_added.html.erb
> +  <%= "Date of #{activity.metadata['event_type']}:" %> <%= activity.metadata["date"] ? Date.parse(activity.metadata["date"]).to_s(:govuk) : "Unknown" %>
Please change: add method to the corresponding Decorator class to handle presentational layer, have a look at `class AuditActivity::CorrectiveAction::UpdateDecorator < AuditActivity::CorrectiveAction::BaseDecorator`

2021-02-10 17:26 UTC, StupidCodeFactory commented on app/views/investigations/activities/accident_or_incident/_accident_or_incident_updated.html.erb
> +    <%= "Date of #{activity.metadata['event_type']}:" %> <b><%= Date.parse(activity.new_date).to_s(:govuk)%></b><br>
same here all the presentational logic should be in a decorator

2021-02-10 17:26 UTC, StupidCodeFactory commented on db/schema.rb
> +    t.string "type"
Please change: you want to add `null: false`

2021-02-10 17:26 UTC, StupidCodeFactory commented on db/schema.rb
> +    t.integer "product_id"
Please change: foreign keys should not be nullable

2021-02-10 17:26 UTC, StupidCodeFactory commented on app/controllers/investigations/accident_or_incidents_controller.rb
> +      @accident_or_incident_form = AccidentOrIncidentForm.new(accident_or_incident_params)
Please change: So you should implement a factory method to load the form from the active record object, have a look at `TestResultForm.from`
you can then extract the changes from the form object and pass the `changes` hash to the service object. example pattern: https://github.com/UKGovernmentBEIS/beis-opss-psd/blob/master/app/controllers/investigations/corrective_actions_controller.rb#L55-L68

2021-02-10 17:29 UTC, nasirkhanbeis commented
Re-tested above fixes looking good. Just spotted couple more minor issues
1. On validation error on this page, when I click on error summary it doesn't focus the field
2. Click back on incident/accident form, doesn't show pre-filled value 
![image](https://user-images.githubusercontent.com/47983567/107547582-83450500-6bc5-11eb-96e9-9bbf9a4df9a4.png)

2021-02-11 11:33 UTC, StupidCodeFactory commented on app/forms/accident_or_incident_form.rb
> +  attribute :is_date_known
```suggestion
  attribute :is_date_known, :boolean
```

2021-02-11 11:37 UTC, StupidCodeFactory commented on app/services/update_accident_or_incident.rb
> +    severity == "other" ? severity_other : nil
```suggestion
    return severity if severity.inquiry.other?
```

2021-02-11 11:39 UTC, StupidCodeFactory commented on app/views/investigations/accident_or_incidents/_form.html.erb
> +<%= form.govuk_radios :is_date_known, legend: "Do you know when the #{@event_type} happened?", items: [{ text: "Yes", value: "yes", conditional: { html: form.govuk_date_input(:date, legend: "Date of
```suggestion
<%= form.govuk_radios :is_date_known, legend: "Do you know when the #{@form.object.type} happened?", items: [{ text: "Yes", value: "yes", conditional: { html: form.govuk_date_input(:date, legend: "Date of #{@event_type}", hint: "For example, 12 11 2020") } }, { text: "No", value: "no" }] %>
```

2021-02-11 12:23 UTC, nasirkhanbeis commented
add accident/incident audit log to show view product hyperlink- sorry Kyle I just missed this earlier. Just saw in wireframes.

2021-02-11 14:34 UTC, nasirkhanbeis commented
List of issues to address further 
1. Confirmation banner when accident or incident added
2. When a case don't have product then show interim page to add product with hyper link as given below
3. View product hyper link audit log.
4. On validation error on this page, when I click on error summary it doesn't focus the field
5. Click back on incident/accident form, doesn't show pre-filled value
![Uploading image.png…]()

2021-02-12 15:27 UTC, StupidCodeFactory requested changes
@KyleMacPherson you need to attached the product to the activity model. The relationship already exists.

2021-02-12 15:27 UTC, StupidCodeFactory commented on app/models/audit_activity/accident_or_incident/accident_or_incident_updated.rb
> +    return updates["date"]&.second if updates["date"]&.second
Please change: we have been using `hash#dig` to avoid doing this. `update.dig("what ever key", 1)`

2021-02-12 15:27 UTC, StupidCodeFactory commented on app/views/investigations/accident_or_incidents/_form.html.erb
> +<% end %>
Please change: this block's indentation is weird

2021-02-12 15:27 UTC, StupidCodeFactory commented on app/views/investigations/activities/accident_or_incident/_accident_or_incident_added.html.erb
> +  Product: <%= Product.find(activity.metadata["product_id"])&.name  %>
Please change: the product is attached on the audit activity

2021-02-12 15:27 UTC, StupidCodeFactory commented on app/views/investigations/activities/accident_or_incident/_accident_or_incident_updated.html.erb
> +  <% if activity.date_changed? %>
```suggestion
  <% if activity.new_date %>
```

2021-02-12 15:27 UTC, StupidCodeFactory commented on app/views/investigations/activities/accident_or_incident/_accident_or_incident_updated.html.erb
> +    Product: <b><%= Product.find(activity.new_product_id).name %></b><br>
```suggestion
    Product: <b><%= activity.product %></b><br>
```

2021-02-12 15:27 UTC, StupidCodeFactory commented on app/views/investigations/activities/accident_or_incident/_accident_or_incident_updated.html.erb
> +  <% if activity.severity_changed? %>
```suggestion
  <% if activity.new_severity %>
```

2021-02-12 15:27 UTC, StupidCodeFactory commented on app/views/investigations/activities/accident_or_incident/_accident_or_incident_updated.html.erb
> +  <% if activity.usage_changed? %>
```suggestion
  <% if activity.new_usage %>
```

2021-02-12 15:27 UTC, StupidCodeFactory commented on app/views/investigations/activities/accident_or_incident/_accident_or_incident_updated.html.erb
> +  <% if activity.additional_info_changed? %>
```suggestion
  <% if activity.new_additional_info %>
```

2021-02-12 15:27 UTC, StupidCodeFactory commented on app/views/investigations/activities/accident_or_incident/_accident_or_incident_updated.html.erb
> +<div class="govuk-body">
no need for this extra predicate method.

2021-02-12 15:27 UTC, StupidCodeFactory commented on app/models/audit_activity/accident_or_incident/accident_or_incident_updated.rb
> +  def severity_changed?
✂️

2021-02-12 15:27 UTC, StupidCodeFactory commented on app/models/audit_activity/accident_or_incident/accident_or_incident_updated.rb
> +  def product_changed?
✂️

2021-02-12 15:27 UTC, StupidCodeFactory commented on app/models/audit_activity/accident_or_incident/accident_or_incident_updated.rb
> +  def date_changed?
✂️

2021-02-12 15:27 UTC, StupidCodeFactory commented on app/models/audit_activity/accident_or_incident/accident_or_incident_updated.rb
> +    updates["date"]&.second || updates["is_date_known"].count == 2
Please use `Hash#dig`, for consistency with the rest of the code:
```suggestion
    updates.dig("date", 1) || updates.dig("is_date_known").count == 2
```

and same for the rest of the file.

2021-02-12 15:27 UTC, StupidCodeFactory commented on app/services/add_accident_or_incident_to_case.rb
> +      metadata: audit_activity_metadata,
Please change: @KyleMacPherson you need to attached the product to the audit activity

2021-02-12 15:28 UTC, StupidCodeFactory commented on app/models/audit_activity/accident_or_incident/accident_or_incident_added.rb
> +      product_id: accident_or_incident.product_id,
✂️  no need for the is the product should be/ must be associated with the audit activity record

2021-02-13 19:39 UTC, KyleMacPherson commented on app/models/audit_activity/accident_or_incident/accident_or_incident_updated.rb
> +  def severity_changed?
This is needed in `views/investigations/activities/accident_or_incident/_accident_or_incident_updated.html.erb`

2021-02-13 19:40 UTC, KyleMacPherson commented on app/models/audit_activity/accident_or_incident/accident_or_incident_updated.rb
> +  def product_changed?
This is needed in `views/investigations/activities/accident_or_incident/_accident_or_incident_updated.html.erb`

2021-02-13 19:48 UTC, KyleMacPherson commented on app/models/audit_activity/accident_or_incident/accident_or_incident_updated.rb
> +  def date_changed?
This is needed in `views/investigations/activities/accident_or_incident/_accident_or_incident_updated.html.erb`

2021-02-13 19:53 UTC, KyleMacPherson commented on app/models/audit_activity/accident_or_incident/accident_or_incident_updated.rb
> +    updates["date"]&.second || updates["is_date_known"].count == 2
`&.second` is actually used throughout the audit activity updated classes so I think this is actually consistent. Examples in risk_level_updated.rb, test_result_updated.rb, risk_assessment_updated.rb.

2021-02-13 19:59 UTC, KyleMacPherson commented on app/models/audit_activity/accident_or_incident/accident_or_incident_updated.rb
> +    return updates["date"]&.second if updates["date"]&.second
`&.second` is actually used throughout the audit activity updated classes so I think this is actually consistent. Examples in risk_level_updated.rb, test_result_updated.rb, risk_assessment_updated.rb.

2021-02-15 14:10 UTC, StupidCodeFactory approved these changes

2021-02-16 14:23 UTC, nasirkhanbeis approved these changes
Re-tested all the fixes, looking all good as expected.

2021-02-16 16:22 UTC, merged