Notifying country
UKGovernmentBEIS/beis-opss-psd pull request #1224
Opened 2021-03-04 17:49 UTC by KyleMacPherson

## Description

## Checklist:
- [ ] Have you documented your changes in the pull request description?
- [ ] Does the change present any security considerations?
- [ ] Is any gem functionality overloaded? Eg: Devise controller methods being overloaded.
- [ ] Has acceptance criteria been tested by a peer?
- [ ] Has the CHANGELOG been updated? (If change is worth telling users about.)

### General testing (author)
- [ ] Test without JavaScript
- [ ] Test on small screen

### Accessibility testing (author)
- [ ] Works keyboard only
- [ ] Tested with one screen reader
- [ ] Zoom page to 400% - content still visible
- [ ] Disable CSS - does content make sense and appear in a logical order?

2021-03-05 11:05 UTC, slorek requested changes
Please change: add the `notifying_country` to the case spreadsheet export template.

2021-03-05 11:05 UTC, slorek commented on lib/tasks/backfill_team_countries.rb
> +      team.update(country: team_to_country[team.name])
Suggestion: throw an exception if the value is `nil`.

Perhaps there should be a presence validation on the `Team` model.

2021-03-05 11:05 UTC, slorek commented on spec/features/create_allegation_as_opss_user_spec.rb
> +  let(:team) { create(:team, country: "Iceland") }
Suggestion: Set a default `country` on the team factory.

And also a default `notifying_country` on the investigation factories.

So that the generated data better reflects real world usage.

2021-03-05 11:05 UTC, slorek commented on app/controllers/investigations/project_controller.rb
> +    @investigation.notifying_country = current_user.team.country
Suggestion: presence validation on the `Investigation` model for `notifying_country`.

2021-03-05 11:05 UTC, slorek commented on lib/tasks/backfill_team_countries.rb
> +      team.update(country: team_to_country[team.name])
Please change: We also need to backfill `notifying_country` on all cases where the team or one of its users was the case creator.

2021-03-08 10:25 UTC, KyleMacPherson commented on app/controllers/investigations/project_controller.rb
> +    @investigation.notifying_country = current_user.team.country
Good call but would prefer to do this in a later PR if you don't mind. I think if we do it now then until the migration is successfully run users won't be able to create cases, so if the migration doesn't work properly first time we could have an issue!

2021-03-08 17:28 UTC, nasirkhanbeis approved these changes
looking good as expected.

2021-03-09 16:34 UTC, slorek commented on lib/tasks/backfill_team_countries.rb
> +      team.update(country: team_to_country[team.name])
We probably want to use `update!` here to ensure exceptions are raised if validation fails.

2021-03-09 16:34 UTC, slorek commented on lib/tasks/backfill_team_countries.rb
> +      investigation.update(notifying_country: investigation.creator_team.country)
We probably want to use `update!` here to ensure exceptions are raised if validation fails.

2021-03-09 16:34 UTC, slorek commented on lib/tasks/backfill_team_countries.rb
> +      }
These values may not match with those in the `govuk-country-and-territory-autocomplete` node module. For example, United Kingdom is expressed as `country:GB` and other countries are expressed in the same format using their ISO country code (see https://github.com/alphagov/govuk-country-and-territory-autocomplete/blob/master/dist/location-autocomplete-canonical-list.json). We might consider using codes as described in https://en.wikipedia.org/wiki/ISO_3166-2:GB

2021-03-09 16:34 UTC, slorek commented on lib/tasks/create_organisation.rake
> +    result = CreateOrganisationWithTeamAndAdminUser.call(org_name: ENV.fetch("ORG_NAME"), admin_email: ENV.fetch("ADMIN_EMAIL"), country: ENV.fetch("COUNTRY"))
Please update the docs in doc/tasks.md.

2021-03-09 18:57 UTC, KyleMacPherson commented on lib/tasks/backfill_team_countries.rb
> +      }
Ah great call, thanks @slorek 👌

2021-03-10 16:27 UTC, KyleMacPherson commented on app/controllers/investigations/allegation_controller.rb
> +    set_notifying_country
Nice! Was looking for where I should do this but couldn't seem to find the right spot, this is perfect, thanks @slorek

2021-03-11 16:57 UTC, slorek approved these changes
Just a couple of suggestions. Thanks for the good work!

2021-03-11 16:57 UTC, slorek commented on app/models/country.rb
> +      all + ADDITIONAL_COUNTRIES
Do we want to sort this list after adding the additional countries?

2021-03-11 16:57 UTC, slorek commented on spec/factories/investigations.rb
> +    notifying_country     { "country:GB" }
We should be able to remove this as `CreateCase` is called in the `before(:create)` callback.

2021-03-12 14:57 UTC, nasirkhanbeis commented
Re-tested on review app, looking good as expected. Give me shout when this is merged, I will do sanity check on prod.

2021-03-12 15:39 UTC, merged