Edit notifying country
UKGovernmentBEIS/beis-opss-psd pull request #1249
Opened 2021-03-15 18:32 UTC by KyleMacPherson

https://trello.com/c/ilAkOSEO/942-5-ability-to-change-notifying-country

## Description

## Checklist:
- [ ] Have you documented your changes in the pull request description?
- [ ] Does the change present any security considerations?
- [ ] Is any gem functionality overloaded? Eg: Devise controller methods being overloaded.
- [ ] Has acceptance criteria been tested by a peer?
- [ ] Has the CHANGELOG been updated? (If change is worth telling users about.)

### General testing (author)
- [ ] Test without JavaScript
- [ ] Test on small screen

### Accessibility testing (author)
- [ ] Works keyboard only
- [ ] Tested with one screen reader
- [ ] Zoom page to 400% - content still visible
- [ ] Disable CSS - does content make sense and appear in a logical order?

2021-03-16 16:50 UTC, nasirkhanbeis commented
tested this on review app, looking good as expected, just the notification to be send to teams added rather to case owner

2021-03-17 10:53 UTC, slorek requested changes
Good work. Just some minor changes.

2021-03-17 10:53 UTC, slorek commented on app/controllers/investigations/notifying_country_controller.rb
> +      @investigation = Investigation.find_by!(pretty_id: params[:investigation_pretty_id]).decorate
We have run into problems passing decorated objects around before where the decorator changes behaviour. This instance is passed to `NotifyingCountryForm` and `UpdateNotifyingCountry`. Suggest removing the `decorate` call here and delaying it until just before views are rendered.

2021-03-17 10:53 UTC, slorek commented on app/controllers/investigations/notifying_country_controller.rb
> +      @notifying_country_form = NotifyingCountryForm.new(country: params["investigation"]["country"])
Suggest using Rails strong parameters instead of referring to the `params` directly.

2021-03-17 10:53 UTC, slorek commented on app/controllers/investigations/ts_investigations_controller.rb
> +    @investigation.notifying_country = current_user.team.country
I don't think this is needed since it is done in `CreateCase`.

2021-03-17 10:53 UTC, slorek commented on app/decorators/audit_activity/investigation/update_notifying_country_decorator.rb
> +  end
Not sure we need this decorator since these methods are present in the model, which I think is the appropriate place as these methods are not transforming the data.

2021-03-17 10:53 UTC, slorek commented on app/models/audit_activity/investigation/update_notifying_country.rb
> +  # Do not send investigation_updated mail. This is handled by the ChangeRiskValidation service
```suggestion
  # Do not send investigation_updated mail. This is handled by the UpdateNotifyingCountry service
```

2021-03-17 10:53 UTC, slorek commented on app/models/user.rb
> +  def is_notifying_country_editor?
I think we want to move away from using the `is_` prefix. One benefit is when using Rspec matchers such as `be_X`. Prefer `notifying_country_editor?` or `can_edit_notifying_country?` as used on `can_validate_risk_level?`.

2021-03-17 10:53 UTC, slorek commented on app/services/update_notifying_country.rb
> +class UpdateNotifyingCountry
For consistency with other services which change an individual case property, suggest `ChangeCaseNotifyingCountry`.

2021-03-17 10:53 UTC, slorek commented on app/services/update_notifying_country.rb
> +    context.changes_made = false
Suggest removing this as it's not used anywhere.

2021-03-17 10:53 UTC, slorek commented on app/forms/notifying_country_form.rb
> +  validates :country, presence: true
Suggestion: we could also validate that the supplied value is in the `Country.notifying_countries` list.

2021-03-19 13:34 UTC, slorek commented on spec/features/change_notifying_country_spec.rb
> +RSpec.feature "Adding and removing business to a case", :with_stubbed_mailer, :with_stubbed_elasticsearch do
```suggestion
RSpec.feature "Changing the notifying country of a case", :with_stubbed_mailer, :with_stubbed_elasticsearch do
```

2021-03-19 13:42 UTC, slorek approved these changes
Just some suggestions to make but otherwise looks good. Thanks!

2021-03-19 13:42 UTC, slorek commented on spec/features/change_notifying_country_spec.rb
> +      sign_in_and_visit_change_notifying_country_page("England")
Suggestion: it would be beneficial to test that the notifying country is shown as `England` on the case overview page and clicking the `Change` link there, and also checking that `England` is the pre-populated value on the form.

2021-03-19 13:42 UTC, slorek commented on spec/features/change_notifying_country_spec.rb
> +      expect(page.find("dt", text: "Notifying country")).to have_sibling("dd", text: "Scotland")
Suggestion: Check we are on the case overview page before making content assertions, as this would help debug a failing test for example if the form showed a validation error.

2021-03-19 13:42 UTC, slorek commented on spec/models/audit_activity/investigation/change_notifying_country_spec.rb
> +    context "when the case'scountry has not been updated" do
```suggestion
    context "when the case's country has not been updated" do
```

2021-03-19 13:42 UTC, slorek commented on app/models/audit_activity/investigation/change_notifying_country.rb
> +    "Notifying country changed from #{previous_country} to #{new_country}"
Suggestion: remove the `#body` method and move this text to the view template.

2021-03-19 13:42 UTC, slorek commented on spec/models/audit_activity/investigation/change_notifying_country_spec.rb
> +    context "when the case'scountry has not been updated" do
This isn't a use case we should ever encounter so I'm not sure we need to test for this.

2021-03-19 13:42 UTC, slorek commented on app/models/audit_activity/investigation/change_notifying_country.rb
> +  def previous_country
Add a test for this method.

2021-03-19 13:42 UTC, slorek commented on app/models/audit_activity/investigation/change_notifying_country.rb
> +  def new_country
Add a test for this method.

2021-03-19 14:34 UTC, KyleMacPherson commented on spec/features/change_notifying_country_spec.rb
> +      sign_in_and_visit_change_notifying_country_page("England")
If I understand what you are saying correctly I believe that is tested in the `sign_in_and_visit_change_notifying_country_page`.

2021-03-22 11:06 UTC, merged