Safety and compliance
UKGovernmentBEIS/beis-opss-psd pull request #1266
Opened 2021-03-24 15:46 UTC by KyleMacPherson

## Description

## Checklist:
- [ ] Have you documented your changes in the pull request description?
- [ ] Does the change present any security considerations?
- [ ] Is any gem functionality overloaded? Eg: Devise controller methods being overloaded.
- [ ] Has acceptance criteria been tested by a peer?
- [ ] Has the CHANGELOG been updated? (If change is worth telling users about.)

### General testing (author)
- [ ] Test without JavaScript
- [ ] Test on small screen

### Accessibility testing (author)
- [ ] Works keyboard only
- [ ] Tested with one screen reader
- [ ] Zoom page to 400% - content still visible
- [ ] Disable CSS - does content make sense and appear in a logical order?

2021-03-26 18:18 UTC, nasirkhanbeis commented
spotted few issues
1. safe and compliant is default selected when I click change for existing OPSS cases
2. When I don't change but simply click change, then I am not suppose to see confirmation banner

2021-03-29 16:13 UTC, nasirkhanbeis approved these changes
re-tested on review app 1266, looking good as expected.

2021-03-30 11:06 UTC, StupidCodeFactory requested changes

2021-03-30 11:06 UTC, StupidCodeFactory commented on app/services/change_safety_and_compliance_data.rb
> +    end
Suggestion: all the logic `should/could` be calculated in the form object. Seems like it form logic creeping up in the service class. but it's debatable.

2021-03-30 11:06 UTC, StupidCodeFactory commented on app/services/change_safety_and_compliance_data.rb
> +      email = entity.is_a?(Team) ? entity.team_recipient_email : entity.email
✂️

2021-03-30 11:06 UTC, StupidCodeFactory commented on app/services/change_safety_and_compliance_data.rb
> +        email,
```suggestion
        entity.email,
```

`Team#email` is aliased to team_recipeint_email

2021-03-30 11:06 UTC, StupidCodeFactory commented on spec/features/change_safety_and_compliance_spec.rb
> +  let(:investigation)  { create(:allegation, creator: user, reported_reason: "unsafe_and_non_compliant", hazard_type: "Burns", hazard_description: "FIRE FIRE FIRE", non_compliant_reason: "Covered in
```suggestion
  let(:investigation)  { create(:allegation, creator: user, reported_reason: "unsafe_and_non_compliant", hazard_type: "Burns", hazard_description: "FIRE! FIRE! FIRE! ", non_compliant_reason: "Covered in petrol") }
```

2021-03-30 11:06 UTC, StupidCodeFactory commented on spec/services/change_safety_and_compliance_data_spec.rb
> +            expect(activity_entry.metadata).to eql({
```suggestion
            expect(activity_entry.metadata).to eq({
```

2021-03-30 11:20 UTC, slorek commented on app/controllers/investigations/safety_and_compliance_controller.rb
> +        flash[:success] = "Case information changed." if result.changes_made
We do this elsewhere, for example the case status (open/close case) which I'm working on currently.

2021-03-30 15:41 UTC, StupidCodeFactory commented on spec/features/change_safety_and_compliance_spec.rb
> +  let(:investigation)  { create(:allegation, creator: user, reported_reason: "unsafe_and_non_compliant", hazard_type: "Burns", hazard_description: "FIRE FIRE FIRE", non_compliant_reason: "Covered in
https://www.youtube.com/watch?v=1EBfxjSFAxQ

2021-03-31 09:51 UTC, StupidCodeFactory approved these changes

2021-03-31 11:38 UTC, tobyhughes approved these changes
Checked:
- New section on overview tab
- Correct variables showing (user input for TS cases and `Not provided` for OPSS cases where the input is not required as part of case creation)
- Edit permissions (i.e. can only edit on cases where added to the team with edit permissions)
- Activity timeline
- Case export

All working as expected

2021-03-31 12:39 UTC, merged