Remove product
UKGovernmentBEIS/beis-opss-psd pull request #1294
Opened 2021-04-07 12:23 UTC by KyleMacPherson

## Description

## Checklist:
- [ ] Have you documented your changes in the pull request description?
- [ ] Does the change present any security considerations?
- [ ] Is any gem functionality overloaded? Eg: Devise controller methods being overloaded.
- [ ] Has acceptance criteria been tested by a peer?
- [ ] Has the CHANGELOG been updated? (If change is worth telling users about.)

### General testing (author)
- [ ] Test without JavaScript
- [ ] Test on small screen

### Accessibility testing (author)
- [ ] Works keyboard only
- [ ] Tested with one screen reader
- [ ] Zoom page to 400% - content still visible
- [ ] Disable CSS - does content make sense and appear in a logical order?

2021-04-09 16:09 UTC, nasirkhanbeis approved these changes
Tested this on review app, looks good as expected.
I think we need to discuss button text or leave as is "submit" as remove product doesn't with radio 'No'

2021-04-12 13:05 UTC, StupidCodeFactory requested changes
looks good, just a couple things to tweak. also it would be nice to swap the `have_(text|content)` for the more robust `have_css`

2021-04-12 13:05 UTC, StupidCodeFactory commented on spec/features/remove_product_from_a_case_spec.rb
> +      find("#reason").set(removal_reason)
please change: Use the label to ensure the form remains accessible
```ruby
fill_in "Reason for removing the product from the case", with: removal_reason
```

2021-04-12 14:16 UTC, StupidCodeFactory commented on app/controllers/investigations/products_controller.rb
> +      redirect_to_investigation_products_tab(nil)
you might want to change this and favour default to nil if the flash is not provided

```ruby
 def redirect_to_investigation_products_tab(flash = nil)
    redirect_to investigation_products_path(@investigation), flash: flash
end
  ```

2021-04-12 14:20 UTC, KyleMacPherson commented on app/views/investigations/products/_removal_form.html.erb
> +        <%= form.submit "Submit", class: "govuk-button govuk-button--warning" %>
I believe it is "Remove" on Miro https://miro.com/app/board/o9J_lcaPrYc=/

2021-04-12 14:20 UTC, KyleMacPherson commented on spec/features/remove_product_from_a_case_spec.rb
> +      expect(page).to have_text(product.name)
Nice, thanks Yann

2021-04-12 14:22 UTC, KyleMacPherson commented on app/views/investigations/products/_removal_form.html.erb
> +      <%= form.govuk_radios :remove_product, legend: "Do you want to remove the product from the case", items: [{ text: "Yes", value: "true", conditional: { html: form.govuk_text_area(:reason, hint:
Haha oops!

2021-04-12 15:06 UTC, StupidCodeFactory commented on app/views/investigations/products/_supporting_information_warning.html.erb
> +          Cannot remove product from the case because it's associated with following supporting information
```suggestion
          Cannot remove the product from the case because it's associated with following supporting information
```

2021-04-12 15:11 UTC, KyleMacPherson commented on app/controllers/investigations/products_controller.rb
> +      redirect_to_investigation_products_tab(nil)
Very nice, thanks!

2021-04-12 15:39 UTC, StupidCodeFactory commented on app/views/investigations/activities/product/_destroy.html.erb
> +<% if activity.metadata['reason'] %>
✂️ there should always be a reason so the I think we can remove this`if`

2021-04-12 16:46 UTC, StupidCodeFactory approved these changes

2021-04-13 09:24 UTC, merged