new remove business page
UKGovernmentBEIS/beis-opss-psd pull request #1298
Opened 2021-04-08 16:29 UTC by StupidCodeFactory

## Description

## Checklist:
- [ ] Have you documented your changes in the pull request description?
- [ ] Does the change present any security considerations?
- [ ] Is any gem functionality overloaded? Eg: Devise controller methods being overloaded.
- [ ] Has acceptance criteria been tested by a peer?
- [ ] Has the CHANGELOG been updated? (If change is worth telling users about.)

### General testing (author)
- [ ] Test without JavaScript
- [ ] Test on small screen

### Accessibility testing (author)
- [ ] Works keyboard only
- [ ] Tested with one screen reader
- [ ] Zoom page to 400% - content still visible
- [ ] Disable CSS - does content make sense and appear in a logical order?

2021-04-15 13:37 UTC, StupidCodeFactory commented
![](https://github.trello.services/images/mini-trello-icon.png) [(8) Update remove business behaviour (new version)](https://trello.com/c/EHX478iJ/977-8-update-remove-business-behaviour-new-version)

2021-04-19 08:42 UTC, nasirkhanbeis commented
I think Remove business should be h1? 
![Uploading image.png…]()

2021-04-19 09:01 UTC, nasirkhanbeis commented
@StupidCodeFactory  also h1 should read as Remove {business name}

2021-04-19 13:44 UTC, nasirkhanbeis approved these changes
Re-tested all the fixes, looking good as expected.

2021-04-21 08:20 UTC, tobyhughes commented
Couple of things from me:

- White spacing looks a little weird and we need to remove the  capitalisation on `Business Details`
- Error summary should be above the H1
- `Reason for removing the business from the case` should be a label rather than hint text

![image](https://user-images.githubusercontent.com/56029300/115521020-a275a800-a282-11eb-9bb5-668d433e6776.png)


![image](https://user-images.githubusercontent.com/56029300/115521137-c3d69400-a282-11eb-9847-bb212790bb4e.png)


![image](https://user-images.githubusercontent.com/56029300/115521070-af929700-a282-11eb-9c17-a74a6009fde9.png)

2021-04-21 11:03 UTC, slorek requested changes

2021-04-21 11:03 UTC, slorek commented on bin/rails
> +APP_PATH = File.expand_path('../config/application', __dir__)
Please put these changes in a separate PR

2021-04-21 11:03 UTC, slorek commented on bin/rake
> +load File.expand_path("spring", __dir__)
Please put these changes in a separate PR

2021-04-21 11:03 UTC, slorek commented on bin/spring
> +    # Ignore when Spring is not installed.
Please put these changes in a separate PR

2021-04-21 11:03 UTC, slorek commented on bin/yarn
> +    exec yarn, *ARGV
Please put these changes in a separate PR

2021-04-26 12:48 UTC, slorek requested changes

2021-04-26 12:48 UTC, slorek commented on spec/services/remove_business_from_case_spec.rb
> +    context "when a risk assessemnt is attached to the business" do
```suggestion
    context "when a risk assessment is attached to the business" do
```

2021-04-26 12:48 UTC, slorek commented on app/decorators/audit_activity/business/destroy_decorator.rb
> +      def title(_viewing_user)
We'll need a migration to generate metadata for existing activities if we override the `title` method.

2021-04-29 09:12 UTC, StupidCodeFactory commented on app/controllers/investigations/businesses_controller.rb
> +    @business = investigation.businesses.new(business_params)
I'm aware this is slightly different than the rest of the code. Here a form object would only be used to to run validation so  I figured maybe it's ok to do it like this.
I'm open to suggestions

2021-05-04 10:10 UTC, nasirkhanbeis approved these changes
Re-tested remove business behaviour, looking good as expected. 
Also tested add business in TS and add business to case, looks good.

2021-05-05 10:12 UTC, slorek requested changes
Thanks for tackling this and the valuable refactoring. I've added some comments for suggested changes as I think there are a few things we should address before going ahead for consistency and safety.

2021-05-05 10:12 UTC, slorek commented on app/models/investigation.rb
> +  has_many :businesses, through: :investigation_businesses
👏

2021-05-05 10:12 UTC, slorek commented on lib/tasks/one_off.rake
> +      AuditActivity::Business::Destroy.where(metadata: nil).find_each(&:migrate_to_metadata)
I think it would be worth considering using the metadata migration convention I've introduced in https://github.com/UKGovernmentBEIS/beis-opss-psd/pull/1354 - this will avoid potential errors and can be run more safely at any time after deployment.

2021-05-05 10:12 UTC, slorek commented on app/models/audit_activity/business/destroy.rb
> +    match = title.match(/Removed: (?<tradding_name>.*)/)
`tradding_name` is a typo I think?

2021-05-05 10:12 UTC, slorek commented on app/models/audit_activity/business/destroy.rb
> +    self.metadata = { business: { trading_name: match["tradding_name"] } }
Can we get the other business attributes so it matches new records?

2021-05-05 11:34 UTC, StupidCodeFactory commented on app/controllers/investigations/business_investigations_controller.rb
> +class Investigations::BusinessInvestigationsController < ApplicationController
The first page of the flow uniquely deals with building the `InvestigationBusiness` - just realising now that i've inverted the join model name 🤦  , so yes that could have been indeed confusing. However it seemed adequate to have an `InvestigationBusinessController` for dealing with the building of `InvestigationBusiness` model, seemed pretty much rails text book to me like a scaffold. At least that was the idea behind. It's also generally good practice to have single purpose classes.

So I'm not going to restore `Wicked::Wizard` I find it far more confusing to understand the flow of the requests, hard to debug and generally unhelpful when one can just use the regular HTTP forms on a given URL.
Generally, I don't understand what problem this library is trying to solve? 

I'm not a massive fan of fat controller but I'm going to add those two actions to the `Investigation::BusinessController`.

2021-05-05 12:23 UTC, StupidCodeFactory commented on app/forms/add_business_to_case_form.rb
> +class AddBusinessToCaseForm
I'm not convinced `InvestigationBusinessForm` was not a better name.

2021-05-12 10:51 UTC, slorek approved these changes

2021-05-14 10:01 UTC, merged