Product image errors
UKGovernmentBEIS/beis-opss-psd pull request #1300
Opened 2021-04-08 16:52 UTC by KyleMacPherson

https://trello.com/c/ZHYvSo9y/823-fix-error-order-on-other-files-and-attachments-page-in-ts-flow

## Description
Correctly order errors on product image upload page for ts users

## Checklist:
- [ ] Have you documented your changes in the pull request description?
- [ ] Does the change present any security considerations?
- [ ] Is any gem functionality overloaded? Eg: Devise controller methods being overloaded.
- [ ] Has acceptance criteria been tested by a peer?
- [ ] Has the CHANGELOG been updated? (If change is worth telling users about.)

### General testing (author)
- [ ] Test without JavaScript
- [ ] Test on small screen

### Accessibility testing (author)
- [ ] Works keyboard only
- [ ] Tested with one screen reader
- [ ] Zoom page to 400% - content still visible
- [ ] Disable CSS - does content make sense and appear in a logical order?

2021-04-13 14:37 UTC, nasirkhanbeis approved these changes
Tested this on review app, looking good as expected.

2021-04-14 11:16 UTC, slorek commented on app/models/audit_activity/test/test_result_updated.rb
> +      updates["details"]&.second.presence || "Removed"
I think we will need a migration for existing activity records to nilify the values where they are empty for this to work.

2021-04-14 11:16 UTC, slorek requested changes
Looks good, just need to think about migrating existing data I think.

2021-04-14 17:05 UTC, KyleMacPherson commented on app/models/audit_activity/test/test_result_updated.rb
> +      updates["details"]&.second.presence || "Removed"
Ok after some research we don't actually need this after all:
``` 
"".presence => nil
"x".presence => "x"
```

2021-04-15 08:53 UTC, slorek approved these changes
Migration not needed after all.

2021-04-15 13:37 UTC, merged