Visibility flow wip
UKGovernmentBEIS/beis-opss-psd pull request #1340
Opened 2021-04-27 16:11 UTC by KyleMacPherson

## Description

## Checklist:
- [ ] Have you documented your changes in the pull request description?
- [ ] Does the change present any security considerations?
- [ ] Is any gem functionality overloaded? Eg: Devise controller methods being overloaded.
- [ ] Has acceptance criteria been tested by a peer?
- [ ] Has the CHANGELOG been updated? (If change is worth telling users about.)

### General testing (author)
- [ ] Test without JavaScript
- [ ] Test on small screen

### Accessibility testing (author)
- [ ] Works keyboard only
- [ ] Tested with one screen reader
- [ ] Zoom page to 400% - content still visible
- [ ] Disable CSS - does content make sense and appear in a logical order?

2021-04-30 13:08 UTC, slorek requested changes
This is a good opportunity to refactor the code, to remove the `create_audit_activity_for_visibility` callback on the `Investigation` model and use service object to handle the creation of activity and notifications. This work is very similar to that done on #1292 for reference. In particular, for consistency we should consider having separate endpoints for making a case unrestricted or restricted, as we have done with close and re-open.

2021-05-07 09:39 UTC, slorek approved these changes
Thanks for this, we are nearly there in removing all the callbacks and being able to refactor the `Activity` classes. Just a few minor comments to check before merging.

2021-05-07 09:39 UTC, slorek commented on app/decorators/audit_activity/investigation/update_visibility_decorator.rb
> +    User.find(source.user_id).name
```suggestion
    source.user.name
```

2021-05-07 09:39 UTC, slorek commented on app/models/investigation.rb
> -  after_update :create_audit_activity_for_visibility
🙌

2021-05-07 09:39 UTC, slorek commented on app/services/change_case_visibility.rb
> +    (email_recipients_for_case_owner + email_recipients_for_case_creator).uniq
I'm not sure we need to notify the case creator for this change. I think the current behaviour for this activity type is the default as defined in `Activity` (implemented as `email_recipients_for_case_owner`).

2021-05-07 09:39 UTC, slorek commented on app/forms/change_case_visibility_form.rb
> +    errors.add(:new_visibility, :same_as_existing, case_type: case_type, visibility: new_visibility) if new_visibility == old_visibility
I think this is a change in behaviour, let's check with @DH02 that we want to throw an error instead of accepting the form when the restriction hasn't changed.

2021-05-07 09:51 UTC, slorek commented on app/forms/change_case_visibility_form.rb
> +    errors.add(:new_visibility, :same_as_existing, case_type: case_type, visibility: new_visibility) if new_visibility == old_visibility
Ignore this, I didn't look at the designs!

2021-05-07 10:51 UTC, KyleMacPherson commented on app/forms/change_case_visibility_form.rb
> +    errors.add(:new_visibility, :same_as_existing, case_type: case_type, visibility: new_visibility) if new_visibility == old_visibility
Cool, thanks @slorek, I think I will let Nas have a last look over this on Monday then merge then if he is happy!

2021-05-07 15:07 UTC, nasirkhanbeis approved these changes
re-tested this on review app, looks all good as expected.

2021-05-10 08:47 UTC, merged