Case owner final
UKGovernmentBEIS/beis-opss-psd pull request #1381
Opened 2021-05-12 14:35 UTC by KyleMacPherson

## Description

## Checklist:
- [ ] Have you documented your changes in the pull request description?
- [ ] Does the change present any security considerations?
- [ ] Is any gem functionality overloaded? Eg: Devise controller methods being overloaded.
- [ ] Has acceptance criteria been tested by a peer?
- [ ] Has the CHANGELOG been updated? (If change is worth telling users about.)

### General testing (author)
- [ ] Test without JavaScript
- [ ] Test on small screen

### Accessibility testing (author)
- [ ] Works keyboard only
- [ ] Tested with one screen reader
- [ ] Zoom page to 400% - content still visible
- [ ] Disable CSS - does content make sense and appear in a logical order?

2021-05-14 08:31 UTC, nasirkhanbeis approved these changes
Tested this on review app, looks all good to me.

2021-05-14 12:34 UTC, DH02 commented
Different HTML, including:
1.	Attribute missing from Form
2.	Different class on parent grid column
3.	The main title is different
4.	Missing title legend elements
5.	The fieldset is missing
6.	The main hint text HTML is different 
7.	The hint text is different and missing a full stop
8.	Form group div in wrong place
9.	Continue button has been wrapping in a form group
10.	Continue button is currently an input type=button (use a hidden input for value if required)
11.	The inline hint text for OPSS incident management doesn’t’ is missing the described by attributes and logic
12.	The inline hint text for OPSS incident management is using the wrong html element and is missing classes (wrong text size)
13.	The inline hint text for OPSS incident management is missing the full stop.

* Its become apparent that the list has hidden/expanding form select options – these non-gds styles can be picked up (and HTML improved) on the sitewide audit. (Until then we can keep the parent class govuk-grid-column-two-thirds-from-desktop to manage the ajax select forms)
* The sitewide habit of having a lone text hyperlink below the action button (inside paragraph tags?) can be reviewed/corrected during a sitewide audit.
* Toby: not sure about the sub-title “Enquiry: 2105-005” here, but that can be reviewed as part of a sitewide audit. Also, a more elegant accessibility compliant design solution can be found to avoid the JavaScript selects? I’m not even sure why we’re using them as the standard fall back (JavaScript disabled version) is much better?

2021-05-21 10:02 UTC, slorek commented
Bug spotted: OPSS Incident Management is shown twice in the list.

![image](https://user-images.githubusercontent.com/408371/119120219-f27f9000-ba23-11eb-9420-0f7a5a852e6c.png)

2021-05-21 10:20 UTC, slorek requested changes

2021-05-21 10:20 UTC, slorek commented on app/assets/stylesheets/_opss.scss
> +.opss-radios__divider--title .govuk-radios__divider,
Unless we create a new bona fide component, I think we're supposed to use the `.app-` prefix as used elsewhere  to override design system components (some code is inconsistent, we also use the `.psd-` prefix but I think this is legacy code) - see https://design-system.service.gov.uk/get-started/extending-and-modifying-components/.

2021-05-21 10:20 UTC, slorek commented on app/controllers/investigations/ownership_controller.rb
> +      Team.where("name IN (?)", ["OPSS Enforcement", "OPSS Incident Management", "OPSS Trading Standards Co-ordination", "OPSS Operational support unit"])
I think we should use the existing `Team.get_visible_teams(current_user)` method (as used in the current code) which is configured in `config/important_team_names.yml` unless there is a reason not to? I think it provides this functionality. If we're not using we should remove this method and config file as I don't think it's used elsewhere, but I am uncomfortable with having names hardcoded in code.

2021-05-21 10:20 UTC, slorek commented on app/controllers/investigations/ownership_controller.rb
> +    @other_teams_added_to_case = Team.find(@investigation.collaboration_accesses.where("type IN (?)", ["Collaboration::Access::Edit", "Collaboration::Access::ReadOnly"]).map(&:collaborator_id))
You could consider using the `changeable` scope here rather than hardcoding class names.
```suggestion
    @other_teams_added_to_case = Team.find(@investigation.collaboration_accesses.changeable).map(&:collaborator_id))
```
Or perhaps look at the `Investigation#teams_with_edit_access` and `Investigation#teams_with_read_only_access` associations and make another combined one.

2021-05-21 15:26 UTC, DH02 commented on app/assets/stylesheets/_opss.scss
> +.opss-radios__divider--title .govuk-radios__divider,
Thanks - the provided link does recommend using a prefix (which opss- is). It uses "app-" as an example. This is taken from the page: 

"When writing code for your application, use a different prefix, **_like_** app-. If your department has its own design resources, they should use a new separate prefix. It’s a good idea to use departmental initials, like hmcts- or dvla-."

.opss- gives me a clean control for uninfected styles. Eventually we'll be able to remove legacy styles (app or psd).

2021-05-24 11:14 UTC, DH02 commented on app/controllers/investigations/ownership_controller.rb
> +    @other_teams_added_to_case = Team.find(@investigation.collaboration_accesses.where("type IN (?)", ["Collaboration::Access::Edit", "Collaboration::Access::ReadOnly"]).map(&:collaborator_id))
@KyleMacPherson I've now merged into the prototypes master changes to the CSS as highlighted by @slorek . 

This has removed a new class that was overriding a govuk class. The HTML/sass has been updated on page: 
case-owner-change-page/improve-case-owner-change-page

<div ="govuk-radios__divider **opss-width-100**">
 
Please add class .opss-width-100 to the .govuk-radios__divider DIVs and get the latest sass from the opss-psd sass file.

2021-05-26 13:09 UTC, slorek requested changes
Bugs look to be resolved, thanks.

Just a small change needed I believe.

2021-05-26 13:09 UTC, slorek commented on app/controllers/investigations/ownership_controller.rb
> +    end
This logic is already implemented in `Team.get_visible_teams`
```suggestion
    Team.get_visible_teams(current_user)
```

2021-05-26 18:47 UTC, KyleMacPherson commented on app/controllers/investigations/ownership_controller.rb
> +    end
@slorek done!

2021-05-27 10:13 UTC, slorek approved these changes

2021-05-27 14:35 UTC, merged