Improve search results
UKGovernmentBEIS/beis-opss-psd pull request #1383
Opened 2021-05-13 14:13 UTC by StupidCodeFactory

## Description

This improves the search efficiency by applying a logic whereby if two words are searched for the search will perform and exact match but also search for exact match of the two terms individually in the across fields (fields are attributes in the Elasticsearch jargon comparing to ActiveRecord).

2021-05-13 14:27 UTC, StupidCodeFactory commented on app/services/elasticsearch_query.rb
> +        type: "cross_fields",
this is allows to "fallback" to cross field match

2021-05-14 13:40 UTC, nasirkhanbeis commented
Tested this on review app and spotted few issues
1. two and word and more search is returning accurate along with other single word match too, however when I search by single keyword it should return exact match on the top in search result - see attached screen shot.
![image](https://user-images.githubusercontent.com/47983567/118278844-56ed9d00-b4c2-11eb-90ba-644e04760f4b.png)

2. Business search - when I search by empty keyword field it is returning on ABC business , expected to return all the businesses in search result page.

2021-05-14 14:12 UTC, nasirkhanbeis commented
Also I see, two word search isn't returning the accurate search results. 
e.g I have products name "Smile Spot Sorria Sempre Teeth whitening" and "Smile spot" when I search by keyword " Smile spot" I don't see exact match search result see screen below 
![image](https://user-images.githubusercontent.com/47983567/118282938-b8b00600-b4c6-11eb-9d55-6eed9a830f27.png)

2021-05-15 20:32 UTC, KyleMacPherson requested changes

2021-05-15 20:32 UTC, KyleMacPherson commented on app/services/elasticsearch_query.rb
>        multi_match: {
Do we need this to be a multi_match? Seems like we are only exact matching by one field (pretty_id)

2021-05-15 20:32 UTC, KyleMacPherson commented on app/services/elasticsearch_query.rb
> +        operator: "or"
This operator should be "and" shouldn't it? As the trello card states the issue is: ```Currently, when a user searches for something if they add more than one word in the search box elastic search uses OR not AND. So as a use adds more terms the search becomes less precise. Contrary to user expectations.```

2021-05-15 20:32 UTC, KyleMacPherson commented on spec/services/elasticsearch_query_spec.rb
> +            investigation_four
If I am reading the trello card correctly `investigation_three` and `investigation_four` should be filtered out in this case

2021-05-17 10:43 UTC, StupidCodeFactory commented
@nasirkhanbeis  this was PR index not being correctly indexed.

<img width="1366" alt="image" src="https://user-images.githubusercontent.com/100796/118476171-79272b00-b70d-11eb-9b83-9b07c37c78d3.png">

2021-05-17 14:37 UTC, closed without merging