Change radio button on edit corrective action
UKGovernmentBEIS/beis-opss-psd pull request #1413
Opened 2021-06-01 15:30 UTC by KyleMacPherson

https://trello.com/c/qk5MQogL/688-update-edit-corrective-action-behaviour-and-activity-log-file-upload-removal

## Description
It seems the only remaining work that needed to be done on the ticket above was to dynamically render the text for the no option on the question "Are there any files related to the action?" to say "Remove attached file" if there is an existing file attached to the corrective action being edited.

## Checklist:
- [ ] Have you documented your changes in the pull request description?
- [ ] Does the change present any security considerations?
- [ ] Is any gem functionality overloaded? Eg: Devise controller methods being overloaded.
- [ ] Has acceptance criteria been tested by a peer?
- [ ] Has the CHANGELOG been updated? (If change is worth telling users about.)

### General testing (author)
- [ ] Test without JavaScript
- [ ] Test on small screen

### Accessibility testing (author)
- [ ] Works keyboard only
- [ ] Tested with one screen reader
- [ ] Zoom page to 400% - content still visible
- [ ] Disable CSS - does content make sense and appear in a logical order?

2021-06-02 10:46 UTC, nasirkhanbeis commented
spotted minor issue, when same file is attached then audit log shows empty log record. Expected not to show any changes when replaced with same file.

2021-06-03 16:52 UTC, nasirkhanbeis approved these changes
Tested this on review app, finally appears all good. Nice work @KyleMacPherson 
there are some further improvements needed which I will raise as separate ticket.

2021-06-07 13:04 UTC, slorek requested changes

2021-06-07 13:04 UTC, slorek commented on app/services/update_corrective_action.rb
> +      remove_blanks_from_changes
I think this should go in the form class as it is sanitising user input. We have a helper called `SanitizationHelper` which can do this. An example of usage is here https://github.com/UKGovernmentBEIS/beis-opss-psd/blob/master/app/forms/corrective_action_form.rb#L54

2021-06-07 13:04 UTC, slorek commented on app/views/investigations/activities/corrective_action/_update.erb
>    <% if activity.business_updated? %>
Not a big one, but as a rule we should be reading the `business_id` in the `metadata` property. The extra relationships on activity models were added a long time ago to patch over an inflexible model, and will ideally be removed in the near future.

2021-06-07 15:33 UTC, KyleMacPherson commented on app/services/update_corrective_action.rb
> +      remove_blanks_from_changes
This example usage is actually in place here, the issue is that we were setting this value to nil via the sanitisation (and also via a method in the update_corrective_action class, but the record on creation is being saved with the file description value as an empty string. I have made some changes to make this uniform across both create and update and removed any sanitisation being done in the update_corrective_action class.

Let me know what you think!

2021-06-08 11:01 UTC, slorek approved these changes

2021-06-08 15:27 UTC, merged