Comments refactor
UKGovernmentBEIS/beis-opss-psd pull request #1420
Opened 2021-06-07 10:56 UTC by KyleMacPherson

## Description

## Checklist:
- [ ] Have you documented your changes in the pull request description?
- [ ] Does the change present any security considerations?
- [ ] Is any gem functionality overloaded? Eg: Devise controller methods being overloaded.
- [ ] Has acceptance criteria been tested by a peer?
- [ ] Has the CHANGELOG been updated? (If change is worth telling users about.)

### General testing (author)
- [ ] Test without JavaScript
- [ ] Test on small screen

### Accessibility testing (author)
- [ ] Works keyboard only
- [ ] Tested with one screen reader
- [ ] Zoom page to 400% - content still visible
- [ ] Disable CSS - does content make sense and appear in a logical order?

2021-06-11 13:23 UTC, slorek requested changes

2021-06-11 13:23 UTC, slorek commented on app/controllers/comments_controller.rb
> +    @investigation = Investigation.find_by!(pretty_id: params[:investigation_pretty_id]).decorate
We've learned it's safer to delay the `decorate` call until just before any view is rendered because the decorator can alter behaviour of the object. In this case we're passing a decorated object to the `AddCommentToCase` service class which in the past has caused us unexpected issues.

2021-06-11 13:23 UTC, slorek commented on app/controllers/comments_controller.rb
>        p[:body] = ActionController::Base.helpers.sanitize(p[:body])
Suggestion: Might be worth moving the sanitisation to the form object in a `before_validation` block, since we do this elsewhere to strip whitespace for example.

2021-06-11 13:23 UTC, slorek commented on app/models/audit_activity/comment/add_comment.rb
> +  end
Suggestion: Move these presentation methods to a decorator and use I18n.

2021-06-11 13:23 UTC, slorek commented on app/models/audit_activity/comment/add_comment.rb
> +class AuditActivity::Comment::AddComment < AuditActivity::Base
Suggestion: Since the comment is on a case it would make sense for this to live in the `AuditActivity::Investigation` namespace.

2021-06-11 13:23 UTC, slorek commented on app/models/comment_activity.rb
>  class CommentActivity < Activity
I think we should create a one-off Rake task to migrate the existing `CommentActivity` data to the new class with the body move to the metadata property, and add a `TODO` comment to this file to remove it once the data is migrated.

2021-06-11 13:23 UTC, slorek commented on app/services/add_comment_to_case.rb
> +    "#{source.show(recipient)} commented on the allegation."
```suggestion
    "#{source.show(recipient)} commented on the #{investigation.case_type}."
```

2021-06-11 13:33 UTC, nasirkhanbeis commented
comment h1 in activity log is wrong, it should  read as "Comment added"
![image](https://user-images.githubusercontent.com/47983567/121694228-d79fb900-cac1-11eb-945d-5fc636609991.png)

2021-06-11 13:40 UTC, slorek commented on app/models/audit_activity/comment/add_comment.rb
> +    "Add comment"
```suggestion
    "Comment added"
```
To match existing behaviour.

2021-06-11 13:40 UTC, slorek commented on app/models/audit_activity/comment/add_comment.rb
> +    "Added"
```suggestion
    "Comment added"
```
To match existing behaviour.

2021-06-14 10:31 UTC, slorek approved these changes

2021-06-14 10:31 UTC, slorek commented on app/controllers/comments_controller.rb
> +    @investigation = @investigation.decorate
No need to decorate before a redirect.

2021-06-14 11:19 UTC, merged