Add email refactor
UKGovernmentBEIS/beis-opss-psd pull request #1432
Opened 2021-06-10 11:49 UTC by KyleMacPherson

## Description

## Checklist:
- [ ] Have you documented your changes in the pull request description?
- [ ] Does the change present any security considerations?
- [ ] Is any gem functionality overloaded? Eg: Devise controller methods being overloaded.
- [ ] Has acceptance criteria been tested by a peer?
- [ ] Has the CHANGELOG been updated? (If change is worth telling users about.)

### General testing (author)
- [ ] Test without JavaScript
- [ ] Test on small screen

### Accessibility testing (author)
- [ ] Works keyboard only
- [ ] Tested with one screen reader
- [ ] Zoom page to 400% - content still visible
- [ ] Disable CSS - does content make sense and appear in a logical order?

2021-06-17 13:25 UTC, nasirkhanbeis commented
spotted few issues: 
1. When replaced with same file, it shows changes with same file- expected not to show any changes when replaced with sam file
2. When To or From is updated , it records empty log
3. when email subject and body is entered and remove the email file then audit log shows Body in new line, layout issue. should show in same line I think. see attached screen shot. 
![image](https://user-images.githubusercontent.com/47983567/122405232-c817e880-cf77-11eb-9e41-6fa5a318d46d.png)

2021-06-23 10:50 UTC, slorek requested changes
Let's leave migration of old data for another day as it will require quite complex pattern matching.

2021-06-23 10:50 UTC, slorek commented on app/services/add_email_to_case.rb
> +      title: correspondence.overview,
The `title` attribute in the database is deprecated. Let the decorator generate the title. This should be stored as `nil`.

2021-06-23 10:50 UTC, slorek commented on app/services/add_email_to_case.rb
> +  end
```suggestion
```

Doesn't appear to be used.

2021-06-23 15:59 UTC, slorek requested changes

2021-06-23 15:59 UTC, slorek commented on app/decorators/audit_activity/correspondence/add_email_decorator.rb
> +        object.metadata["overview"]
Please change: `metadata` will be `nil` for legacy activity records. This will throw an error in that case.

2021-06-23 15:59 UTC, slorek commented on app/decorators/audit_activity/correspondence/add_email_decorator.rb
> +        Date.parse(metadata["correspondence_date"]).to_s(:govuk)
Please change: `metadata` will be `nil` for legacy activity records. This will throw an error in that case.

2021-06-23 19:10 UTC, KyleMacPherson commented on app/decorators/audit_activity/correspondence/add_email_decorator.rb
> +        object.title
Is this what you were looking for @slorek?

2021-06-24 15:10 UTC, slorek commented on app/decorators/audit_activity/correspondence/add_email_decorator.rb
> +        object.correspondence_date
I can't see where this is defined in the model. For legacy activities it is buried in a text string in the `body`.

2021-06-24 20:15 UTC, KyleMacPherson commented on app/decorators/audit_activity/correspondence/add_email_decorator.rb
> +        object.correspondence_date
I was confused by why this works so have been looking into it and it turns out we don't need this to handle old AuditActivity entries for adding email. This is because in `app/views/investigations/activities/_activity_card.html.erb` on lines 38-44 we render the body as a whole if we do not have any metadata for an activity:

```  <% else %>
    <% if activity.metadata %>
      <%= render "investigations/activities/#{activity.template_name}", activity: activity %>
    <% else  %>
      <% if activity.body %>
        <%= markdown simple_format(activity.body) %>
      <% end %>```

2021-06-25 14:02 UTC, slorek approved these changes

2021-06-28 08:45 UTC, merged