Refactor alert
UKGovernmentBEIS/beis-opss-psd pull request #1443
Opened 2021-06-17 15:46 UTC by KyleMacPherson

## Description

## Checklist:
- [ ] Have you documented your changes in the pull request description?
- [ ] Does the change present any security considerations?
- [ ] Is any gem functionality overloaded? Eg: Devise controller methods being overloaded.
- [ ] Has acceptance criteria been tested by a peer?
- [ ] Has the CHANGELOG been updated? (If change is worth telling users about.)

### General testing (author)
- [ ] Test without JavaScript
- [ ] Test on small screen

### Accessibility testing (author)
- [ ] Works keyboard only
- [ ] Tested with one screen reader
- [ ] Zoom page to 400% - content still visible
- [ ] Disable CSS - does content make sense and appear in a logical order?

2021-06-18 14:55 UTC, nasirkhanbeis approved these changes
Looks good as expected!

2021-06-23 10:34 UTC, slorek requested changes
Good work, just a bit of tidying up needed.

2021-06-23 10:34 UTC, slorek commented on app/controllers/investigations/alerts_controller.rb
> +    @user_count = number_with_delimiter(User.active.count, delimiter: ",")
```suggestion
    set_user_count
```

2021-06-23 10:34 UTC, slorek commented on app/controllers/investigations/alerts_controller.rb
> +    if @alert_form.valid?
Please change: need to handle invalid input.

2021-06-23 10:34 UTC, slorek commented on app/controllers/investigations/alerts_controller.rb
>      authorize @investigation, :send_email_alert?
```suggestion
  def set_and_authorize_investigation
    @investigation = Investigation.find_by!(pretty_id: params[:investigation_pretty_id])
    authorize @investigation, :send_email_alert?
```

2021-06-23 10:34 UTC, slorek commented on app/controllers/investigations/alerts_controller.rb
>    before_action :set_investigation
```suggestion
```
This is duplicated in the individual action methods.

2021-06-23 10:34 UTC, slorek commented on app/controllers/investigations/alerts_controller.rb
> +    authorize @investigation, :investigation_restricted?
Suggestion: We could possibly avoid having to do this by using a named finder scope on `Investigation` which limits to non-restricted cases.

2021-06-23 10:34 UTC, slorek commented on app/forms/alert_form.rb
> +  attribute :user_count
```suggestion
```
Doesn't appear to be used.

2021-06-23 10:34 UTC, slorek commented on app/controllers/investigations/alerts_controller.rb
> +          user_count: @user_count
Suggestion: Let the service object calculate this. Simplifies the interface so that it can be re-used more easily. The query will be cached anyway so there's very little performance implication.

2021-06-23 10:34 UTC, slorek commented on app/forms/alert_form.rb
> +  def summary_validation
```suggestion
private

  def summary_validation
```

I'd move the `default_` methods to private as well if you implement the getter override suggestion.

2021-06-23 10:34 UTC, slorek commented on app/views/investigations/alerts/new.html.erb
> +                 value: (@alert_form.description.presence || @alert_form.default_description),
Suggestion: Override the `description` getter in the form to return `default_description` if no `description` set. Removes logic from the view.

2021-06-23 10:34 UTC, slorek commented on app/views/investigations/alerts/new.html.erb
> +                 value: (@alert_form.summary.presence || @alert_form.default_summary) %>
Suggestion: Override the `summary` getter in the form to return `default_summary` if no summary set. Removes logic from the view.

2021-06-23 10:34 UTC, slorek commented on app/models/audit_activity/alert/add.rb
> +    }
I think we would want to store an `Integer` here - I think at the moment it would store a string passed through from the controller. I don't think we need to pass through the count at all.

```suggestion
  def self.build_metadata(alert)
    {
      user_count: User.active.count,
      subject: alert.summary,
      date_sent: alert.created_at,
      description: alert.description
    }
```

2021-06-23 10:34 UTC, slorek commented on app/models/audit_activity/alert/add.rb
>    extend ActionView::Helpers::NumberHelper
```suggestion
```
I don't think we need this any more.

2021-06-23 10:34 UTC, slorek commented on app/services/add_alert.rb
> +    emails = User.active.map(&:email)
Suggestion: Put this as a new method in the `EntitiesToNotify` concern so that it is in one place.

2021-06-23 10:34 UTC, slorek commented on app/services/add_alert.rb
> +    AuditActivity::Alert::Add.build_metadata(alert, user_count)
```suggestion
    AuditActivity::Alert::Add.build_metadata(alert)
```
Don't need to pass this through from the controller.

2021-06-23 10:34 UTC, slorek commented on app/views/investigations/activities/alert/_add.html.erb
> +</div>
Use `strong` and `p` instead of `b` and double`br` tags.

2021-06-23 10:42 UTC, slorek commented
Bug spotted: If submitting the form with default values, the following is displayed:

<img width="696" alt="Screenshot 2021-06-23 at 11 42 06" src="https://user-images.githubusercontent.com/408371/123083620-20d3ff00-d418-11eb-9c01-ae2fff53b2a7.png">

2021-06-23 19:22 UTC, KyleMacPherson commented on app/controllers/investigations/alerts_controller.rb
> +          user_count: @user_count
👍 One side affect of this is that we won't render the number of users that the alert was sent to in the flash success message, I personally don't think it is an issue but just FYI

2021-06-23 19:24 UTC, KyleMacPherson commented on app/views/investigations/alerts/new.html.erb
> +                 value: (@alert_form.description.presence || @alert_form.default_description),
I'm struggling trying to get this to work, is there an example of where we do this is the codebase already?

2021-06-23 22:46 UTC, KyleMacPherson commented on app/controllers/investigations/alerts_controller.rb
> +    render :new unless @alert_form.valid?
Good spot, thanks Steve. Added assertions to check for this in the feature spec.

2021-06-24 11:17 UTC, slorek commented on app/controllers/investigations/alerts_controller.rb
> +          user_count: @user_count
We could potentially return this count in the service object context for use in the flash message.

2021-06-24 11:24 UTC, slorek commented on app/views/investigations/alerts/new.html.erb
> +                 value: (@alert_form.description.presence || @alert_form.default_description),
There's some similar override usage in https://github.com/UKGovernmentBEIS/beis-opss-psd/blob/master/app/forms/risk_assessment_form.rb and https://github.com/UKGovernmentBEIS/beis-opss-psd/blob/master/app/forms/product_form.rb#L60-L85.

I think the method in the form class would look something like:

```ruby
def description
  return super if self[:description].present?
  default_description
end
```

2021-06-25 13:58 UTC, slorek commented on app/controllers/investigations/alerts_controller.rb
> +      render :new
```suggestion
      @investigation = @investigation.decorate
      render :new
```
I think we need to decorate here.

2021-06-25 13:58 UTC, slorek commented on app/controllers/investigations/alerts_controller.rb
> +    @investigation = Investigation.find_by!(pretty_id: params[:investigation_pretty_id])
```suggestion
    @investigation = Investigation.not_private.find_by!(pretty_id: params[:investigation_pretty_id])
```
Adding a `not_private` scope to `Investigation` would negate the need to use `authorize @investigation, :investigation_restricted?` everywhere.

2021-06-25 13:58 UTC, slorek commented on app/forms/alert_form.rb
> +
Suggestion: Something like this would negate the need to check and revert to default in the view.

```ruby
def summary
  self[:summary] || default_summary
end

def description
  self[:description] || default_description
end

private
```

2021-06-25 13:58 UTC, slorek commented on app/views/investigations/alerts/new.html.erb
> +                 value: (@alert_form.summary.presence || @alert_form.default_summary) %>
```suggestion
                 value: @alert_form.summary %>
```

2021-06-25 13:58 UTC, slorek commented on app/views/investigations/alerts/new.html.erb
> +                 value: (@alert_form.description.presence || @alert_form.default_description),
I've added an example as a suggestion.

2021-06-25 13:58 UTC, slorek commented on app/views/investigations/alerts/new.html.erb
> +                 value: (@alert_form.description.presence || @alert_form.default_description),
```suggestion
                 value: @alert_form.description,
```

2021-06-28 10:53 UTC, slorek approved these changes

2021-06-29 09:47 UTC, merged