Change cases search sort options to a dropdown
UKGovernmentBEIS/beis-opss-psd pull request #1649
Opened 2021-11-08 09:21 UTC by stdstaff

https://trello.com/c/AR5zgCsB/1170-update-sort-by-on-cases-page3

## Description
Update the Cases page to a newer visual design. This moves "sort by" to a dropdown on the right hand side, and changes the sort logic.

- On the initial page load of the cases page, select 'blank', but this implies "recent"
- Never show the "relevant" option
- Maintain state (keep whatever sort the user has perviously selected when applying new filters)
- If the user has 'blank' set and there's been a keyword search, the sort should still display the 'blank' option, but this should switch to mean "relevant"

## Checklist:
- [ ] Have you documented your changes in the pull request description?
- [ ] Does the change present any security considerations?
- [ ] Is any gem functionality overloaded? Eg: Devise controller methods being overloaded.
- [ ] Has acceptance criteria been tested by a peer?
- [ ] Has the CHANGELOG been updated? (If change is worth telling users about.)

### General testing (author)
- [ ] Test without JavaScript
- [ ] Test on small screen

### Accessibility testing (author)
- [ ] Works keyboard only
- [ ] Tested with one screen reader
- [ ] Zoom page to 400% - content still visible
- [ ] Disable CSS - does content make sense and appear in a logical order?

2021-11-09 16:47 UTC, nasirkhanbeis approved these changes
Tested this on the review app, Sort by dropdown works as expected. 
Also, verified the non-js version, combination with other filters and keyword search, 
sort option is retained in the session which I think is good.

2021-11-12 10:58 UTC, KyleMacPherson commented on spec/models/search_params_spec.rb
> +      it "returns relevant if there is a query present" do
[Minor] I would add another context for clarity here

```context "when sort_by is blank" do
        context "when there is a query present" do
        end

        context "when there is no search query present" do
        end
end```

2021-11-12 11:25 UTC, KyleMacPherson approved these changes

2021-11-12 11:49 UTC, slorek requested changes
I think we are missing a scenario in the feature spec describing the sorting behaviour when keywords are entered.

I'd also like to review the behaviour with Darren and Toby before this is introduced as I feel the changes may be confusing.

2021-11-16 10:36 UTC, stdstaff commented on spec/models/search_params_spec.rb
> +      it "returns relevant if there is a query present" do
:+1: https://github.com/UKGovernmentBEIS/beis-opss-psd/pull/1649/commits/5ddb635b9c966b7eec9dbf146478841ef217c679

2021-11-17 11:22 UTC, stdstaff commented
This logic has been reviewed internally and it is felt further investigation is required into how best to present sort options to service users, and into how to implement this technically. Marking this PR "DO NOT MERGE" pending the results of these discussions.

2021-11-24 12:50 UTC, KyleMacPherson approved these changes

2021-11-24 15:29 UTC, slorek approved these changes

2021-11-25 12:01 UTC, nasirkhanbeis approved these changes
Tested this on the review app, looking good as expected. Nice work Nick!

2021-11-25 12:58 UTC, merged