WIP: Supporting info page new
UKGovernmentBEIS/beis-opss-psd pull request #1930
Opened 2022-06-20 14:08 UTC by KyleMacPherson

## Description

## Checklist:
- [ ] Have you documented your changes in the pull request description?
- [ ] Does the change present any security considerations?
- [ ] Is any gem functionality overloaded? Eg: Devise controller methods being overloaded.
- [ ] Has acceptance criteria been tested by a peer?
- [ ] Has the CHANGELOG been updated? (If change is worth telling users about.)

### General testing (author)
- [ ] Test without JavaScript
- [ ] Test on small screen

### Accessibility testing (author)
- [ ] Works keyboard only
- [ ] Tested with one screen reader
- [ ] Zoom page to 400% - content still visible
- [ ] Disable CSS - does content make sense and appear in a logical order?

2022-06-24 15:14 UTC, nasirkhanbeis approved these changes
Tested this on the review app, looking all good as expected.

2022-06-29 13:33 UTC, slorek requested changes
Good work! Just some minor amendments requested, thanks!

2022-06-29 13:33 UTC, slorek commented on app/assets/stylesheets/opss/_opss-shared.scss
> +input[type="checkbox"]:disabled + label {opacity: 1 !important; }*/
✂️

2022-06-29 13:33 UTC, slorek commented on app/assets/stylesheets/opss/_opss-shared.scss
> +    } */
✂️

2022-06-29 13:33 UTC, slorek commented on app/assets/stylesheets/opss/_opss-psd.scss
> +        /*float: right;*/
✂️

2022-06-29 13:33 UTC, slorek commented on app/assets/stylesheets/opss/_opss-shared.scss
> +            }*/
✂️

2022-06-29 13:33 UTC, slorek commented on app/assets/stylesheets/opss/_opss-shared.scss
> +                    /*position: relative; top: -1px;*/
✂️

2022-06-29 13:33 UTC, slorek commented on app/controllers/investigations/record_emails_controller.rb
> +      AddEmailToCase.call(
```suggestion
      AddEmailToCase.call!(
```
Throws exception on failure, otherwise we will not know if it failed and may erroneously report to the user that it succeeded.

2022-06-29 13:33 UTC, slorek commented on app/controllers/investigations/corrective_actions_controller.rb
> +      UpdateCorrectiveAction.call(
```suggestion
      UpdateCorrectiveAction.call!(
```
Since we removed the `success` conditional. Throws exception on failure, otherwise we will not know if it failed and may erroneously report to the user that it succeeded.

2022-06-29 13:33 UTC, slorek commented on app/controllers/investigations/supporting_information_controller.rb
> +      @grouped_supporting_information = {
It might be more performant given the size of the production database to slice this after the initial query, rather than doing multiple database queries.

2022-06-29 13:33 UTC, slorek commented on app/controllers/investigations/test_results_controller.rb
> +    UpdateTestResult.call(
```suggestion
    UpdateTestResult.call!(
```
Since we removed the `success` conditional. Throws exception on failure, otherwise we will not know if it failed and may erroneously report to the user that it succeeded.

2022-06-29 13:33 UTC, slorek commented on app/forms/supporting_information_type_form.rb
> +  IMAGE_TYPE = { image: "Case image", }.freeze
```suggestion
  IMAGE_TYPE = { image: "Case image" }.freeze
```

2022-06-29 13:33 UTC, slorek commented on app/views/investigations/supporting_information/_card.html.erb
> +              </span-->
```suggestion
```

2022-06-29 13:33 UTC, slorek commented on app/views/investigations/supporting_information/_card.html.erb
> +<li>
Indentation is inconsistent in this file.

2022-06-29 13:33 UTC, slorek commented on app/views/investigations/supporting_information/index.html.erb
> +<%= render "investigations/pages_top", investigation: @investigation %>
Indentation is inconsistent in this file.

2022-06-29 13:33 UTC, slorek commented on app/views/investigations/tabs/_supporting_information.erb
> -<%= page_title "Supporting information - #{@investigation.pretty_id}" %>
Indentation is inconsistent in this file.

2022-06-29 15:48 UTC, KyleMacPherson commented on app/controllers/investigations/supporting_information_controller.rb
> +      @grouped_supporting_information = {
I believe calling `investigation.supporting_information` just makes all the same database queries so i don't think it will negatively effect performance vs our current implementation.

2022-07-01 09:50 UTC, slorek approved these changes

2022-07-01 10:16 UTC, merged