WIP: Edit risk assessments
UKGovernmentBEIS/beis-opss-psd pull request #846
Opened 2020-08-20 15:12 UTC by frankieroberto

Ability to edit and update risk assessments.

2020-08-25 12:29 UTC, tobyhughes commented
Getting unexpected behaviour when trying to edit 'Who completed the assessment?'.

Steps to replicate:

1) Add risk assessment
2) Select 'Someone else' on 'Who completed the assessment?' radio and complete free text
3) Complete remaining fields and submit
4) Edit risk assessment
5) Change 'Who completed the assessment?' radio to {my team} or {other team} and submit changes
6) Updated team not showing on view page or on case overview

2020-08-25 21:11 UTC, frankieroberto commented
@tobyhughes good catch! The error is because the old free text value isn't being wiped (and having both a free text value and a team is invalid). Will fix.

2020-08-27 11:34 UTC, frankieroberto commented
@tobyhughes the bug has been fixed in b438bd9. Please re-test whenever you're ready.

2020-08-27 11:37 UTC, frankieroberto commented on app/controllers/investigations/risk_assessments_controller.rb
> +          risk_assessment_file: @risk_assessment_form.risk_assessment_file,
These are being set from the form explicitly, rather than via `@risk_assessment_form.attributes.merge({})`, as that bypasses the attribute getter override methods, which are required in order to ignore values such as `assessed_by_other` when they're not relevant (but the browser still submits them).

2020-08-27 17:14 UTC, StupidCodeFactory approved these changes

2020-08-27 17:14 UTC, StupidCodeFactory commented on app/decorators/audit_activity/risk_assessment/risk_assessment_updated_decorator.rb
> +    if new_risk_level.present? && new_risk_level != "other"
```suggestion
    return I18n.t(".investigations.risk_level.show.levels.#{new_risk_level}") if !other?
```

2020-08-27 17:14 UTC, StupidCodeFactory commented on app/models/audit_activity/risk_assessment/risk_assessment_updated.rb
> +    updates["assessed_by_team_id"]&.second
i've done this for the corrective action 
```suggestion
    updates.dig("assessed_by_team_id", 1)
```

2020-08-28 10:16 UTC, slorek approved these changes

2020-08-28 10:16 UTC, slorek commented on app/models/audit_activity/risk_assessment/risk_assessment_updated.rb
> +  def notify_relevant_users; end
Minor suggestion: This method can be `private`. I suspect a number of the other methods could be as well.

2020-08-28 10:16 UTC, slorek commented on app/models/audit_activity/risk_assessment/risk_assessment_updated.rb
> +    raise "Deprecated - use AddRiskAssessmentToCase.call instead"
Minor suggestion:
```suggestion
    raise "Deprecated - use UpdateRiskAssessment.call instead"
```

2020-08-28 10:16 UTC, slorek commented on app/controllers/investigations/risk_assessments_controller.rb
> +      @risk_assessment_form.attributes = risk_assessment_params
🤔 won't this remove the three attributes you set just above?

2020-08-28 10:31 UTC, KamQureshi approved these changes

2020-09-02 12:37 UTC, slorek commented
🚫 This change introduces a bug where there are validation errors on the add or edit risk assessment form which has a file attached:

https://sentry.io/organizations/beis/issues/1862374593/?environment=psd-pr-846&project=1329381&query=is%3Aunresolved

2020-09-02 13:00 UTC, slorek requested changes
🚫 This change introduces a bug where there are validation errors on the add or edit risk assessment form which has a file attached:

https://sentry.io/organizations/beis/issues/1862374593/?environment=psd-pr-846&project=1329381&query=is%3Aunresolved

There is currently no test coverage of this scenario so I will modify the existing feature specs.

2020-09-04 15:24 UTC, slorek commented on app/controllers/investigations/risk_assessments_controller.rb
> +      @risk_assessment_form.attributes = risk_assessment_params
Update: it doesn't.

2020-09-07 10:37 UTC, slorek approved these changes

2020-09-07 10:37 UTC, merged