WIP: Convert record email correspondence flow to 1 page form
UKGovernmentBEIS/beis-opss-psd pull request #907
Opened 2020-09-24 15:16 UTC by frankieroberto

2020-09-29 12:27 UTC, frankieroberto commented on app/controllers/investigations/record_emails_controller.rb
> +    end
This is duplicated (for the two different attributes) for now. But it'd be nice to extract this somehow. It's also part of the controller as it doesn't feel like it belongs to the form model or the service class. Suggestions welcome!

2020-09-29 13:25 UTC, StupidCodeFactory requested changes
Looks good, just a couple thing:
1. There was a 500 when entering record email date in the future
2. I think it is fine to handle the file upload, like I described in my comments in the form object and un-clutter the controller with a couple `if/else` but up to you if you want to address  that or not

2020-09-29 13:25 UTC, StupidCodeFactory commented on app/assets/javascripts/investigations/attachment_description.js
> +  const attachmentFileInput = $('#attachment-file-input, #email_attachment')
should we change this to  more a more generic class `js-attachmentFileInput` ?

2020-09-29 13:25 UTC, StupidCodeFactory commented on app/controllers/investigations/record_emails_controller.rb
> +      @email_correspondence_form.email_file = ActiveStorage::Blob.create_after_upload!(
I'd move this in a lazy method inside the form. that would find or upload and setting `existing_email_file_id`

2020-09-29 13:25 UTC, StupidCodeFactory commented on app/controllers/investigations/record_emails_controller.rb
> +    end
same for this if/else block

2020-09-29 13:25 UTC, StupidCodeFactory commented on app/services/add_email_to_case.rb
> +    # Update email attachment description
suggestion: remove the comment and create a method `#update_email_attachment_description`

2020-09-29 13:40 UTC, frankieroberto commented
@StupidCodeFactory good catch! Didn't spot the validation as it was on the super class. Validation added to the form object in 1fa670f2ba06cc582b71787cbed786cbaf21eda5

2020-09-29 15:31 UTC, frankieroberto commented on app/assets/javascripts/investigations/attachment_description.js
> +  const attachmentFileInput = $('#attachment-file-input, #email_attachment')
Yeah we should, but I didn't want to break/change the existing code for now.  I'd also quite like to refactor it to avoid jQuery as we barely use it.

2020-09-29 15:33 UTC, frankieroberto commented on app/controllers/investigations/record_emails_controller.rb
> +      @email_correspondence_form.email_file = ActiveStorage::Blob.create_after_upload!(
It felt a bit unexpected to me that a form object would save a file or look up a record using an ID. But maybe it's ok. Think I'll leave it for now until the pattern becomes clearer as other forms need to do this.

2020-09-29 15:45 UTC, StupidCodeFactory approved these changes

2020-09-30 10:14 UTC, slorek reviewed
Nice work, thanks 👏 

There are a couple of comments on things I would like us to do now, but if you prefer to do these as an immediate follow-up PR we can merge this.

2020-09-30 10:14 UTC, slorek commented on app/controllers/investigations/record_emails_controller.rb
> +      @email_correspondence_form.email_file = ActiveStorage::Blob.create_after_upload!(
At the moment the form object's role is to sanitise user input - I don't think it would be too unexpected for it to ensure the uploaded file was processed (and therefore sent for AV scanning), especially as we need that to happen to display the form back to the user. But I'm not bothered whether it's there or in the controller. However, this `create` method is rather long and so it could do with breaking up a bit. We have a number of forms where the file upload is not persisted when there are errors, so a re-usable/repeatable pattern would be ideal.

2020-09-30 10:14 UTC, slorek commented on app/controllers/investigations/record_emails_controller.rb
> +    end
Perhaps something like a `FileConcern` :trollface:

2020-09-30 10:14 UTC, slorek commented on app/services/add_email_to_case.rb
> +    # TODO: refactor into this class
I think we should do this as part of the change (or immediately after) as we have done previously. These audit activity models need to be migrated one by one so we can remove `User.current`.

2020-09-30 10:22 UTC, frankieroberto commented on app/services/add_email_to_case.rb
> +    # TODO: refactor into this class
Agreed. Will do this as a follow-up PR.

2020-09-30 10:56 UTC, nasirkhanbeis approved these changes
looks good as expected, also it doesn't clear the attachment on other field validation errors.

2020-09-30 11:34 UTC, merged