Add GH action for deleting dangling review apps
UKGovernmentBEIS/beis-opss-psd pull request #921
Opened 2020-10-05 15:01 UTC by scruti

## Description

## Checklist:
- [ ] Have you documented your changes in the pull request description?
- [ ] Does the change present any security considerations?
- [ ] Is any gem functionality overloaded? Eg: Devise controller methods being overloaded.
- [ ] Has acceptance criteria been tested by a peer?
- [ ] Has the CHANGELOG been updated? (If change is worth telling users about.)

### General testing (author)
- [ ] Test without JavaScript
- [ ] Test on small screen

### Accessibility testing (author)
- [ ] Works keyboard only
- [ ] Tested with one screen reader
- [ ] Zoom page to 400% - content still visible
- [ ] Disable CSS - does content make sense and appear in a logical order?

2020-10-05 16:04 UTC, slorek commented
I wonder why https://github.com/UKGovernmentBEIS/beis-opss-psd/blob/master/.github/workflows/review-apps-delete.yml is not doing this already.

CF v7 API is stable now so we can change all `cf7` usage to `cf`.

2020-10-05 16:04 UTC, slorek requested changes

2020-10-05 16:04 UTC, slorek commented on .github/workflows/review-apps-delete-dangling.yml
> +        CF_CLI_VERSION: 7.0.0-beta.25
```suggestion
        CF_CLI_VERSION: v7
```

2020-10-05 16:08 UTC, scruti commented
The one/off deletion is currently working, but if it fails once/for a while the rev-apps stay there for the eternity... 
I guess at some point we can just leave the schedule search & clean to avoid duplication.

2020-10-06 10:21 UTC, frankieroberto approved these changes

2020-10-06 10:21 UTC, frankieroberto commented on .github/workflows/review-apps-delete-dangling.yml
> +        echo "::set-env name=ACTIVE_PRS::${active_prs[@]}"
I'm not entirely sure what the difference is, but the GitHub Actions syntax has a [`::set-output`](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter) option which might be useful here?

2020-10-06 10:21 UTC, frankieroberto commented on .github/workflows/review-apps-delete-dangling.yml
> +        active_prs=(`curl -H "Accept: application/vnd.github.groot-preview+json" https://api.github.com/repos/UKGovernmentBEIS/beis-opss-psd/pulls | jq -r '.[] | "psd-pr-\(.number)"'`)
I think you can use the `$GITHUB_REPOSITORY` var here (in case we ever rename the repo or move it to a different org):

```suggestion
        active_prs=(`curl -H "Accept: application/vnd.github.groot-preview+json" https://api.github.com/repos/$GITHUB_REPOSITORY/pulls | jq -r '.[] | "psd-pr-\(.number)"'`)
```

2020-10-06 10:21 UTC, frankieroberto commented on .github/workflows/review-apps-delete-dangling.yml
> +        cf logout
Suggest moving the auth commands to their own step at the beginning, with a logout step at the end, to remove duplication?

2020-10-07 10:13 UTC, scruti commented on .github/workflows/review-apps-delete-dangling.yml
> +        echo "::set-env name=ACTIVE_PRS::${active_prs[@]}"
Need to update this as the `::set-env` got recently deprecated.

2020-10-07 10:15 UTC, scruti commented on .github/workflows/review-apps-delete-dangling.yml
> +        cf logout
As each step runs in an independent shell I assumed the CF session wouldn't be kept between steps. Will give it a try when updating the syntax.

2020-10-08 12:06 UTC, scruti commented on .github/workflows/review-apps-delete-dangling.yml
> +        cf logout
@frankieroberto actually worked. Good one!

2020-10-08 16:24 UTC, frankieroberto approved these changes

2020-10-09 14:03 UTC, slorek approved these changes

2020-10-09 18:47 UTC, merged