WIP: Ability to edit emails
UKGovernmentBEIS/beis-opss-psd pull request #923
Opened 2020-10-06 12:50 UTC by frankieroberto

2020-10-29 10:03 UTC, nasirkhanbeis commented
Had a quick look yesterday and found a bug

2020-10-30 09:36 UTC, nasirkhanbeis commented
wondering when user want to change the uploaded file then there's no way unless they select remove and edit again 
Suggestion: we still need choose file input next to uploaded file
![image](https://user-images.githubusercontent.com/47983567/97689294-454b2780-1a93-11eb-9dcc-2dbdefb8c6b0.png)

2020-10-30 10:06 UTC, frankieroberto commented
@nasirkhanbeis the bug should have been fixed - thanks for spotting that.

You're right that there's currently no way to select a different file if after selecting a replacement file but getting a validation error. Whilst we could keep the file input below the currently selected file, I was worried that this would introduce confusion, and there would also be no way, once selecting a 3rd file, to change your mind and stick with the one you uploaded before. Another option I considered was adding a 4th radio button, like this:

```
Replace or remove file

( ) Keep current file
( ) Remove file
( ) Use replacement file: filename.pdf
( ) Upload a different file
```

...but that might be even more confusing!

It's a tricky edge case! I suggest that we keep this as-is for now, as it seems _fairly_ unlikely that a user would want to swap the file again after getting a validation error, and if that happens, they can always re-edit the record anyway.

2020-10-30 11:03 UTC, nasirkhanbeis commented
> Had a quick look yesterday and found a bug, submit edit email form with empty body and subject field with Remove email file option, it is throwing 422 error

Hi @frankieroberto  Found another bug around this behaviour . steps to replicate

1. email with no body or subject, click edit
2. select remove radio and submit, throws expected error 
3. Now select radio keep and submit , it still throws error.

2020-10-30 13:41 UTC, frankieroberto commented
@nasirkhanbeis thanks, that bug has been fixed now too.

2020-10-30 14:23 UTC, nasirkhanbeis commented
looks all good now, just few minor issues around activity log otherwise all good. Re: design I'm still not convinced from user point however Toby's call. 
No activity log on below field changes 
Email attachment with no attachment description
Email Summary 
Email subject 
Email body

2020-10-30 16:26 UTC, slorek requested changes
Nice! Just a few minor comments.

2020-10-30 16:26 UTC, slorek commented on app/controllers/investigations/record_emails_controller.rb
> +      @email_correspondence_form.email_attachment_action = "keep" if @email_correspondence_form.email_attachment.present?
Suggestion: this logic should probably be encapsulated by the form object.

2020-10-30 16:26 UTC, slorek commented on app/models/audit_activity/correspondence/email_updated.rb
> +class AuditActivity::Correspondence::EmailUpdated < AuditActivity::Base
Please change: I'm a bit confused why we aren't inheriting from `AuditActivity::Correspondence::Base`. Especially as that defines the `correspondence` relationship. Perhaps we need an explanatory comment.

2020-10-30 16:26 UTC, slorek commented on app/models/audit_activity/correspondence/email_updated.rb
> +  end
I think this is not needed if we are inheriting from `AuditActivity::Base` as we have not inherited a `from` method.

2020-10-30 16:26 UTC, slorek commented on app/models/audit_activity/correspondence/email_updated.rb
> +class AuditActivity::Correspondence::EmailUpdated < AuditActivity::Base
Please change: I think we need to override the private `notify_relevant_users` method as we have in other activity models. Otherwise the `after_save :notify_relevant_users` callback inherited from `Activity` will generate extra emails which have an empty body. Our tests should also be checking that no extra emails are being generated. It will be nice when we can finally eliminate this mess!

2020-10-30 16:26 UTC, slorek commented on app/services/update_email.rb
> +  def entities_to_notify
Please change: Use `EntitiesToNotify#email_recipients_for_case_owner` from #987

2020-10-30 16:26 UTC, slorek commented on spec/features/edit_email_spec.rb
> +  end
Suggestion: We could also lightly test that emails have been sent here.

2020-10-30 16:26 UTC, slorek commented on spec/services/update_email_spec.rb
> +  let(:user) { create(:user, name: "User 2", team: team) }
Suggestion: I guess this should have an `activated` trait.

2020-10-30 16:26 UTC, slorek commented on spec/services/update_email_spec.rb
> +        end
Please change: Please use the `it_behaves_like "a service which notifies the case owner"` shared examples from #987

2020-10-30 16:34 UTC, slorek requested changes
Bug: Attachment description is always showing in the activity summarywhen it has not changed (remained blank).
<img width="415" alt="Screenshot 2020-10-30 at 16 32 30" src="https://user-images.githubusercontent.com/408371/97732018-cf17e680-1acd-11eb-94cb-3764d9dc8313.png">

2020-10-30 16:34 UTC, slorek commented on app/models/audit_activity/correspondence/email_updated.rb
> +class AuditActivity::Correspondence::EmailUpdated < AuditActivity::Base
Please change: define a `title` method for the activity which is displayed on the timeline.
<img width="415" alt="Screenshot 2020-10-30 at 16 32 30" src="https://user-images.githubusercontent.com/408371/97731889-9c6dee00-1acd-11eb-9ce4-ce98231240a3.png">

2020-10-30 16:40 UTC, slorek requested changes

2020-10-30 16:40 UTC, slorek commented on app/services/update_email.rb
> +    AuditActivity::Correspondence::EmailUpdated.create!(
Please change: i think for consistency with other audit activity models we would want to add the `correspondence` object here. Otherwise there's no reference to the actual email that was changed.

2020-10-30 16:57 UTC, frankieroberto commented on app/services/update_email.rb
> +    AuditActivity::Correspondence::EmailUpdated.create!(
Done, thanks. I forgot about the foreign key to correspondence (the activity model has foreign keys to some models but not others... 🤷 )

2020-11-02 10:37 UTC, frankieroberto commented on app/models/audit_activity/correspondence/email_updated.rb
> +class AuditActivity::Correspondence::EmailUpdated < AuditActivity::Base
Done, thanks.

2020-11-02 12:00 UTC, StupidCodeFactory commented on app/services/update_email.rb
> +  end
multiple interactor would make this a lot easier to understand.

2020-11-02 12:08 UTC, nasirkhanbeis commented
looks like there's  no way to change uploaded file in below edit scenario
1. given email which has subject and body fields entered with no attachment, click edit
2. clear subject and body, upload file, change date to invalid
3. Submit form, throws error on the date field which is expected, however returned page doesn't give option to remove, change uploaded file. 
Expected to show choose input field so if needed user can re-upload new file. 
![image](https://user-images.githubusercontent.com/47983567/97866575-14bdf480-1d04-11eb-8784-454746b7dbf0.png)

2020-11-02 12:10 UTC, nasirkhanbeis commented
Also when nothing changed, it still records empty log
Click edit email, don't change anyting but just click update
go to activity log, it shows empty log

2020-11-02 12:24 UTC, frankieroberto commented
> looks like there's no way to change uploaded file in below edit scenario

This should be fixed, thanks.

2020-11-02 16:31 UTC, nasirkhanbeis approved these changes
Looks all good as expected.

2020-11-02 16:55 UTC, slorek approved these changes

2020-11-02 17:04 UTC, merged