Remove model tests
UKGovernmentBEIS/beis-opss-psd pull request #943
Opened 2020-10-12 15:53 UTC by frankieroberto

This removes the final two minitest tests, which were tests on the models.

The functionality was largely already covered by the rspec suite, although I added some quick tests for activity generation on adding and removing a business, as that hasn't been converted to a service class yet.

2020-10-14 09:48 UTC, slorek requested changes
Thanks for doing this. I think there is a bit more work to do to cover the tests being removed.

2020-10-14 09:48 UTC, slorek commented on test/models/investigation_test.rb
> -  end
Looks like we need to implement a unit test for `past_owners`.

2020-10-14 09:48 UTC, slorek commented on test/models/investigation_test.rb
> -  end
Looks like we need a unit test on `view_non_protected_details?` in investigation_policy_spec.rb.

2020-10-14 09:48 UTC, slorek commented on test/models/investigation_test.rb
> -  end
Looks like we need a unit test on `change_owner_or_status?` in investigation_policy_spec.rb.

2020-10-14 09:48 UTC, slorek commented on test/models/investigation_test.rb
> -  end
I think we need a feature spec for closing a case. We have a request spec for this but it doesn't cover activity generation.

2020-10-14 09:48 UTC, slorek commented on test/models/notification_test.rb
> -  end
Same comment as before relating to closing cases - we aren't testing notifications or activity as far as I can see.

2020-10-14 09:48 UTC, slorek commented on test/models/notification_test.rb
> -  end
We should add some tests for email notifications to the feature spec as well.

2020-10-14 11:46 UTC, frankieroberto commented on test/models/notification_test.rb
> -  end
Interesting. We've / I've generally not been testing emails from feature specs, and leaving that to service specs instead.  Although I see that we do have a few feature specs which do test emails.

Personally I find that things like this:

```ruby
notification_email = delivered_emails.last

expect(notification_email.personalization[:updater_name]).to eq("Bob Jones (Portsmouth Trading Standards)")
expect(notification_email.personalization[:optional_message]).to eq("Message from Bob Jones (Portsmouth Trading Standards):\n\n^ Thanks for collaborating on this case with us.")
expect(notification_email.personalization[:investigation_url]).to end_with("/cases/#{investigation.pretty_id}")
```

to be a bit implementation-specific for a feature spec. It'd be nice if we could write feature specs which just make assertions on the rendered content of the email instead, eg something like:

```ruby
expect_email(
  to: "john@example.com",
  subject: "Investigation updated",
  body: "Message from Bob"
)
```

But I'm not sure how we'd do that with Notify... 🤔

2020-10-14 14:06 UTC, frankieroberto commented on test/models/investigation_test.rb
> -  end
Thanks. Done in c08e41326871e8cfb472b3a920f1f1da9d7d35e9.

2020-10-14 14:07 UTC, frankieroberto commented on test/models/investigation_test.rb
> -  end
Thanks, done. See 21453fd059e33521bb17d7e70954161e4d65e2d2.

2020-10-14 14:08 UTC, frankieroberto commented on test/models/investigation_test.rb
> -  end
I've added a new feature spec for this here: 26ca8f8db9e71a1dbeb944933f0f9569bec7cfc1 – also covers activity generation (via checking the Activity page) and emails.

2020-10-14 14:10 UTC, frankieroberto commented on test/models/notification_test.rb
> -  end
I've created an email expectation which abstracts around the Notify mocking here: https://github.com/UKGovernmentBEIS/beis-opss-psd/pull/943/commits/26ca8f8db9e71a1dbeb944933f0f9569bec7cfc1#diff-84f9b40234b7b60c0d51bbced9fd49a9610d55b3a557f48b62245460d97178d1 – let me know what you think.

2020-10-14 14:10 UTC, frankieroberto commented on test/models/notification_test.rb
> -  end
Done now in 26ca8f8db9e71a1dbeb944933f0f9569bec7cfc1

2020-10-15 11:23 UTC, slorek commented on test/models/notification_test.rb
> -  end
Nice!

2020-10-15 11:26 UTC, slorek approved these changes
Thanks, good work on the changes!

2020-10-15 11:39 UTC, merged