make phone call editable
UKGovernmentBEIS/beis-opss-psd pull request #957
Opened 2020-10-19 09:25 UTC by StupidCodeFactory

## Description

## Checklist:
- [ ] Have you documented your changes in the pull request description?
- [ ] Does the change present any security considerations?
- [ ] Is any gem functionality overloaded? Eg: Devise controller methods being overloaded.
- [ ] Has acceptance criteria been tested by a peer?
- [ ] Has the CHANGELOG been updated? (If change is worth telling users about.)

### General testing (author)
- [ ] Test without JavaScript
- [ ] Test on small screen

### Accessibility testing (author)
- [ ] Works keyboard only
- [ ] Tested with one screen reader
- [ ] Zoom page to 400% - content still visible
- [ ] Disable CSS - does content make sense and appear in a logical order?

2020-10-20 13:43 UTC, StupidCodeFactory commented
![](https://github.trello.services/images/mini-trello-icon.png) [Make the phone call correspondence editable](https://trello.com/c/tn6KfVvP/747-make-the-phone-call-correspondence-editable)

2020-10-22 19:48 UTC, frankieroberto requested changes
Looking good! A couple of minor issues to fix.

2020-10-22 19:48 UTC, frankieroberto commented on app/decorators/audit_activity/correspondence/phone_call_updated_decorator.rb
> +      end
Can we avoid the rescue by checking if the value is nil first?

```suggestion
      def new_correspondence_date        
        value = metadata.dig("updates", "correspondence_date", 1)
        return if value.nil?
        Date.parse(value).to_s(:govuk)
      end
```

2020-10-22 19:48 UTC, frankieroberto commented on app/views/investigations/record_phone_calls/_form_fields.html.erb
> +<% end %>
Is this partial used anywhere? Looks like `_form.html.erb` is being used instead?

2020-10-22 19:48 UTC, frankieroberto commented on app/views/investigations/record_phone_calls/_form.html.erb
> +      <%= form.submit form.object.persisted? ? "Update phone call" : "Add phone call", class: "govuk-button" %>
Please change: switch to the `govukButton` helper (which adds the class automatically plus some extra html attributes).

```suggestion
      <%= govukButton text: (form.object.persisted? ? "Update phone call" : "Add phone call") %>
```

2020-10-23 08:33 UTC, StupidCodeFactory commented on app/controllers/investigations/record_phone_calls_controller.rb
> +    correspondence_form.load_transcript_file
Steve was happy to handle this inside the form. It seemed the obvious place since we need to do this dance to be able to persist the file across multiple form submissions. Hence I went ahead in my previous PR and implemented this inside the form object.

2020-10-23 08:35 UTC, StupidCodeFactory commented on app/decorators/audit_activity/correspondence/phone_call_updated_decorator.rb
> +      end
The value can still raise an exception and I'm not certain this is more readable so I'm going to keep it this way.

2020-10-23 08:39 UTC, StupidCodeFactory commented on app/forms/phone_call_correspondence_form.rb
> +  attribute :id
I don't think it provides a lot of value
1. You'd have to prefix every attributes to be consistant and remain clear what attributes are for what model
2. _prefix_\_id is usually used to denote an associated object to the one in the current scope. 
In this class it's pretty obvious we are editing a phone call object.

2020-10-23 08:44 UTC, StupidCodeFactory commented on app/forms/phone_call_correspondence_form.rb
> +    details&.strip!
I'll add a comment that's indeed not self obvious.

Basically that was done in to remove the line feed that's sent by some browser for text in textareas which would then be picked up as a change even if the field has not changed.

2020-10-23 09:05 UTC, StupidCodeFactory commented on app/services/edit_phone_call.rb
> +  end
I've renamed the method so that it is clearer what he requirements are.

2020-10-23 09:13 UTC, frankieroberto commented on app/controllers/investigations/record_phone_calls_controller.rb
> +    correspondence_form.load_transcript_file
👍  if we're happy to have this logic in the form, it'd be good to port this across to the similar email controller/form at some point soon.

2020-10-23 09:15 UTC, StupidCodeFactory commented on app/forms/phone_call_correspondence_form.rb
> +  end
yes it is a very useful pattern to abstract away the instantiation of an object. It's used a lot everywhere even in Rails , basically when you do `ActiveRecord::Record.create({})` that's a factory pattern.

https://en.wikipedia.org/wiki/Factory_method_pattern

Another good alternative is the builder pattern, for a more complex object setup.

2020-10-23 13:59 UTC, slorek commented on app/controllers/investigations/record_phone_calls_controller.rb
> +    correspondence_form.load_transcript_file
To reiterate I think it's fine because we will need to do certain validations and processing on the attachment as we would any other user input.

2020-10-23 14:24 UTC, slorek requested changes
Looks good, just some minor changes needed which I have noted. Thanks.

2020-10-23 14:24 UTC, slorek commented on app/models/audit_activity/correspondence/phone_call_updated.rb
> +  # no-op sending of email is done by the service AddPhoneCallToCase
```suggestion
  # no-op sending of email is done by the service UpdatePhoneCall
```

2020-10-23 14:24 UTC, slorek commented on app/models/audit_activity/correspondence/phone_call_updated.rb
> +  belongs_to :correspondence, class_name: "Correspondence::PhoneCall"
Please change: Override the `from` method inherited from the parent class (see `AuditActivity::Correspondence::AddMeeting` for the consistent example used elsewhere), or we might be able to remove it completely from the parent class.

2020-10-23 14:24 UTC, slorek commented on app/services/update_phone_call.rb
> +  end
Suggestion: This is inconsistent with the other service classes which raise these errors inline. When I tried this before it didn't reduce the CodeClimate complexity score. I don't have a strong opinion but would prefer consistency.

2020-10-23 14:24 UTC, slorek commented on app/services/update_phone_call.rb
> +    entities_to_notify.each do |entity|
Suggestion: `entities_to_notify` is often different across different business processes, sometimes it's the case creator - in this case it's all teams with access to the case except the current user. If we want to extract this out to reduce duplication I'd suggest renaming `entities_to_notify` to something more specific e.g. `email_recipients_for_team_with_access` (I realise this was done in a previous PR).

2020-10-23 14:24 UTC, slorek commented on app/services/update_phone_call.rb
> +    return unless any_changes?
Please change: Add a unit test for this behaviour.

2020-10-23 14:24 UTC, slorek commented on app/services/update_phone_call.rb
> +      end
Please change: unit tests only cover adding a new file, but this code indicates should test when no file is supplied (should it remove the existing one or keep it?), when the file is identical and when it is different.

2020-10-23 14:33 UTC, frankieroberto commented on app/controllers/investigations/record_phone_calls_controller.rb
> +    correspondence_form.load_transcript_file
I think it's fine too. It's _maybe_ a bit unexpected for the form object to be persisting files and creating associated models, which was why I hesitated, but equally it's also a lot of boilerplate code to have in the controller otherwise.

2020-10-23 16:02 UTC, frankieroberto approved these changes

2020-10-26 11:45 UTC, slorek approved these changes

2020-10-26 15:39 UTC, slorek approved these changes
Just a couple of suggestions.

2020-10-26 15:39 UTC, slorek commented on app/decorators/audit_activity/correspondence/phone_call_updated_decorator.rb
> +      REMOVED = "Removed".freeze
Suggestion: I18n would be a better place to manage the text.

2020-10-26 15:39 UTC, slorek commented on app/decorators/audit_activity/correspondence/phone_call_updated_decorator.rb
> +        metadata.dig("updates", "correspondent_name", 1).presence || REMOVED
Suggestion: We can probably wrap this in a reusable method or replace `nil` in values once at the end.

2020-10-26 16:11 UTC, merged