Fix images not saved for enquiry
UKGovernmentBEIS/beis-opss-psd pull request #982
Opened 2020-10-28 15:02 UTC by StupidCodeFactory

## Description

The `DateConcern` was causing the `Enquiry` model all contain changes. When attaching an document Rails would never call `save` on the object detecting that it had other changes and hence on changing the attributes in memory.
I've removed the `DateConcern` from the `Enquiry` and fixed the Javascript that set date to today or tomorrow.

2020-10-29 15:51 UTC, slorek approved these changes

2020-10-29 17:40 UTC, nasirkhanbeis approved these changes
looks good as expected

2020-10-30 10:48 UTC, frankieroberto requested changes
Looks good, thanks!

Just needs some tweaks to the error messages, I think.

2020-10-30 10:48 UTC, frankieroberto commented on config/locales/en.yml
> +              in_future: Date received of enquiry must be today or in the past
Think these need a bit of re-wording...

Suggestion:

```suggestion
              must_be_real: Date enquiry received must be a real date
              incomplete: Date enquiry received must include a %{missing_date_parts}
              in_future: Date enquiry received must be today or in the past
```

2020-10-30 15:50 UTC, StupidCodeFactory commented on config/locales/en.yml
> +              in_future: Date received of enquiry must be today or in the past
cheers! yes does read much better indeed.

2020-10-30 15:53 UTC, frankieroberto approved these changes

2020-11-02 13:20 UTC, merged