Fix randomly failing test
UKGovernmentBEIS/beis-opss-psd pull request #985
Opened 2020-10-28 17:38 UTC by frankieroberto

These tests sometimes fail due to `Faker::Hipster.word` sometimes randomly producing the same word multiple times, which then get removed by the call to `uniq!` in the model.

Replacing the randomness with fixed strings in order to avoid this, and hopefully make the tests easier to follow.

2020-10-29 10:02 UTC, StupidCodeFactory requested changes
Please change: use `.unique` method https://github.com/faker-ruby/faker#ensuring-unique-values

2020-10-29 11:46 UTC, StupidCodeFactory commented on spec/models/investigation_spec.rb
> -    let(:product_category) { Faker::Hipster.word }
To guaranty uniqueness faker introduced this concept: `Faker::Hipster.unique.word`. 
I see the argument for having plain string to improve readability of the test. 
I prefer the randomness and assigning the result into a `let` variable with a descriptive enough name and use it in the test. Also if you change one the test will break. you'll have to fix the other in a separate test run, it seems more brittle to me.

2020-10-29 11:46 UTC, StupidCodeFactory commented on spec/models/investigation_spec.rb
> -    let(:product_category) { Faker::Hipster.word }
But I dunno what do you prefer @slorek?

2020-10-29 15:53 UTC, slorek commented on spec/models/investigation_spec.rb
> -    let(:product_category) { Faker::Hipster.word }
I prefer to refer to variables by name rather than value, too. Shall we try using `unique`? I haven't seen that before.

2020-10-30 10:32 UTC, frankieroberto commented on spec/models/investigation_spec.rb
> -    let(:product_category) { Faker::Hipster.word }
ok, done. @StupidCodeFactory thanks for pointing out the `.unique` method!

2020-10-30 15:48 UTC, StupidCodeFactory approved these changes
@frankieroberto thanks for the change!

2020-10-30 16:08 UTC, merged